# Generated by Django 5.2.1 on 2025-07-18 15:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the order was created.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='inventory',
            field=models.ForeignKey(help_text='The inventory item (size/variation) being ordered.', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='products.inventory'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_group',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Groups multiple order items from a single checkout event.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Number of units of the inventory item ordered.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('CO', 'Completed')], default='PE', help_text='Current status of the order (e.g., pending, completed).', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(help_text='The user who placed the order.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
