# Generated by Django 5.2.1 on 2025-07-05 12:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_group',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID to group products that belong to the same order'),
        ),
    ]
