# Generated by Django 5.2.1 on 2025-07-10 18:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_order_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_group',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
