# Generated by Django 5.2.1 on 2025-06-26 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_alter_wishlist_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={
                ('user', 'content_type', 'object_id'),
                ('guest_id', 'content_type', 'object_id'),
            },
        ),
    ]
