# Generated by Django 5.2 on 2025-05-02 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Bracelet', 'Bracelet'), ('Earring', 'Earring'), ('Necklace', 'Necklace'), ('Ring', 'Ring')], error_messages={'unique': 'This category already exists.'}, max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Daisy', 'Daisy'), ('Gerbera', 'Gerbera'), ('Forget Me Not', 'Forget Me Not'), ('Lily', 'Lily'), ('Lotus', 'Lotus'), ('Berry', 'Berry'), ('Sunflower', 'Sunflower'), ('Lily of the Valley', 'Lily of the Valley')], error_messages={'unique': 'This collection already exists.'}, max_length=18, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Blue', 'Blue'), ('Green', 'Green'), ('Pink', 'Pink'), ('Red', 'Red'), ('White', 'White'), ('Yellow', 'Yellow')], error_messages={'unique': 'This color already exists.'}, max_length=6, unique=True)),
                ('hex_code', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Yellow Gold', 'Yellow Gold'), ('Rose Gold', 'Rose Gold'), ('Platinum', 'Platinum')], error_messages={'unique': 'This material already exists.'}, max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Stud', 'Stud'), ('Drop', 'Drop'), ('Pendant', 'Pendant'), ('Lariat', 'Lariat'), ('Tennis', 'Tennis'), ('Chain', 'Chain'), ('Statement', 'Statement'), ('Band', 'Band')], error_messages={'unique': 'This reference already exists.'}, max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('One Size', 'One Size')], error_messages={'unique': 'This size already exists.'}, max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Aquamarine', 'Aquamarine'), ('Diamond', 'Diamond'), ('Emerald', 'Emerald'), ('Ruby', 'Ruby'), ('Sapphire', 'Sapphire')], error_messages={'unique': 'This stone already exists.'}, max_length=10, unique=True)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='StonesColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.color')),
                ('stone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.stone')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_image', models.URLField()),
                ('second_image', models.URLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.collection')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.material')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.reference')),
                ('stones_colors', models.ManyToManyField(to='products.stonescolors')),
            ],
        ),
    ]
