# Generated by Django 5.2 on 2025-04-26 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('BR', 'Bracelets'), ('EA', 'Earrings'), ('NE', 'Necklaces'), ('RI', 'Rings')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.CharField(choices=[('CL', 'Classics'), ('DA', 'Daisy'), ('FMN', 'Forget-Me-Not'), ('LI', 'Lily'), ('LO', 'Lotus'), ('RA', 'Radiant'), ('SU', 'Sunflower')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('AQ', 'Aquamarine'), ('BU', 'Blue'), ('GR', 'Green'), ('PI', 'Pink'), ('RE', 'Red'), ('WH', 'White'), ('YE', 'Yellow')], max_length=2)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('YG', 'Yellow Gold'), ('RG', 'Rose Gold'), ('ST', 'Platinum')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_image', models.URLField()),
                ('second_image', models.URLField()),
                ('third_image', models.URLField()),
                ('fourth_image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('OS', 'OS')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Stone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stone', models.CharField(choices=[('DI', 'Diamond'), ('EM', 'Emerald'), ('RU', 'Ruby'), ('SA', 'Sapphire')], max_length=2)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='StoneColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.color')),
                ('stone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.stone')),
            ],
        ),
        migrations.AddField(
            model_name='stone',
            name='colors',
            field=models.ManyToManyField(through='products.StoneColor', to='products.color'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.collection')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.description')),
                ('material', models.ManyToManyField(to='products.material')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.media')),
                ('stone_color', models.ManyToManyField(to='products.stonecolor')),
            ],
        ),
    ]
