# Generated by Django 5.2 on 2025-04-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection',
            field=models.CharField(choices=[('DD', 'Daisy Delight'), ('EW', 'Engagement & Wedding'), ('FMN', 'Forget Me Not'), ('LIB', 'Lily Bloom'), ('LOB', 'Lotus Blossom'), ('RC', 'Radiant Cluster'), ('SU', 'Sunflower')], max_length=3),
        ),
    ]
