# Generated by Django 5.2 on 2025-05-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(choices=[('Daisy', 'Daisy'), ('Gerbera', 'Gerbera'), ('Forget Me Not', 'Forget Me Not'), ('Lily', 'Lily'), ('Lotus', 'Lotus'), ('Leaf', 'Leaf'), ('Berry', 'Berry'), ('Sunflower', 'Sunflower'), ('Lily of the Valley', 'Lily of the Valley'), ('Watch', 'Watch')], error_messages={'unique': 'This collection already exists.'}, max_length=18, unique=True),
        ),
    ]
