# Generated by Django 5.2 on 2025-04-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('BR', 'Bracelet'), ('EA', 'Earring'), ('NE', 'Necklace'), ('RI', 'Ring')], error_messages={'unique': 'This category already exists.'}, max_length=2, unique=True),
        ),
    ]
