# Generated by Django 5.2 on 2025-04-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name_plural': 'Media'},
        ),
        migrations.AddField(
            model_name='media',
            name='fifth_image',
            field=models.URLField(default='asd'),
            preserve_default=False,
        ),
    ]
