# Generated by Django 5.2.1 on 2025-07-31 17:25

import cloudinary.models
import src.accounts.validators.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphoto',
            name='photo',
            field=cloudinary.models.CloudinaryField(
                max_length=255,
                null=True,
                validators=[
                    src.accounts.validators.models.FileSizeValidator(5)
                ],
                verbose_name='image',
            ),
        ),
    ]
