# Generated by Django 5.2 on 2025-04-07 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0003_alter_inventory_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
    ]
