# Generated by Django 5.2 on 2025-04-07 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventories', '0004_alter_inventory_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('content_type', 'object_id', 'size')},
        ),
    ]
