products_data = [
    # BERRY
    {
        'category': 'Stud Earring',
        'collection': 'Berry',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115862/9_zuupv7.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115868/10_ccqces.webp',
        'stone_by_color': 'Blue Sapphire',
        'price': 3600,
        'description': '16 round brilliant diamonds weighing a total of approximately 0.90 carats with round sapphire center stones of approximately 0.44 carats each, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Earring',
        'collection': 'Berry',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115870/7_oxmuys.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115867/8_k1zqeq.webp',
        'stone_by_color': 'Red Ruby',
        'price': 3700,
        'description': '16 round brilliant diamonds weighing a total of approximately 0.90 carats with round ruby center stones of approximately 0.44 carats each, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Earring',
        'collection': 'Berry',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115868/11_ntbstg.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115867/12_re58tf.webp',
        'stone_by_color': 'Green Emerald',
        'price': 3400,
        'description': '10 pear-shaped diamonds weighing a total of approximately 3.35 carats with 6 round emeralds weighing a total of approximately 2.01 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Berry',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115862/5_rlufar.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115867/6_cb1tab.avif',
        'stone_by_color': 'Green Emerald',
        'price': 4400,
        'description': '5 pear-shaped diamonds weighing a total of approximately 2.01 carats with 3 round emeralds weighing a total of approximately 1.39 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Berry',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115867/3_bhkuqr.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115870/4_pbumhb.avif',
        'stone_by_color': 'Blue Sapphire',
        'price': 4600,
        'description': '5 pear-shaped diamonds weighing a total of approximately 2.03 carats with 3 round sapphires weighing a total of approximately 1.86 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Berry',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115868/1_rcfsir.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115870/2_vf7yxw.avif',
        'stone_by_color': 'Red Ruby',
        'price': 4800,
        'description': '5 pear-shaped diamonds weighing a total of approximately 2.03 carats with 3 round rubies weighing a total of approximately 1.88 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Ring',
        'collection': 'Berry',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115867/16_rkceku.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115868/15.avif_fmwmjz.png',
        'stone_by_color': 'Red Ruby',
        'price': 2800,
        'description': '13 round brilliant diamonds weighing a total of approximately 0.64 carats with 13 round rubies weighing a total of approximately 0.81 carats, prong-set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Ring',
        'collection': 'Berry',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115867/14_jaiuit.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115870/13.avif_hc7tnh.png',
        'stone_by_color': 'Blue Sapphire',
        'price': 2600,
        'description': '13 round brilliant diamonds weighing a total of approximately 0.64 carats with 13 round sapphires weighing a total of approximately 0.81 carats, prong-set in platinum.',
        'target_gender': 'F',
    },
    # FORGET ME NOT
    {
        'category': 'Bracelet',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115880/37_yydycy.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115884/38_ebclnr.avif',
        'stone_by_color': 'Blue Sapphire',
        'price': 5200,
        'description': '45 pear-shaped and round brilliant sapphires weighing a total of approximately 4.17 carats and 33 pear-shaped, marquise and round brilliant diamonds weighing a total of approximately 4.24 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Bracelet',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115880/35_tl8ef4.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115874/36_vypeqm.avif',
        'stone_by_color': 'Red Ruby',
        'price': 5400,
        'description': '45 pear-shaped and round rubies weighing a total of approximately 4.43 carats and 33 pear-shaped, marquise and round brilliant diamonds weighing a total of approximately 4.37 carats, set in platinum. ',
        'target_gender': 'F',
    },
    {
        'category': 'Bracelet',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115880/39_ec0wun.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115871/40_jh7chy.avif',
        'stone_by_color': 'Pink Sapphire',
        'price': 5100,
        'description': '45 pear-shaped and round brilliant pink sapphires weighing a total of approximately 4.36 carats and 33 pear-shaped, marquise and round brilliant diamonds weighing a total of approximately 4.24 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Stud Earring',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115871/19_cp3mbf.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115883/20_iumckw.webp',
        'stone_by_color': 'Pink Sapphire',
        'price': 2800,
        'description': '12 pear-shaped pink sapphires weighing a total of approximately 2.20 carats and 2 round brilliant diamonds weighing a total of approximately 0.07 carats, set in platinum.',
        'target_gender': 'F',
    },
    
    ## !!!!!
    {
        'category': 'Stud Earring',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115870/15_wi6mrj.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115883/16_ujqqh5.webp',
        'stone_by_color': 'White Diamond',
        'price': 4100,
        'description': '12 pear-shaped diamonds and 2 round brilliant diamonds weighing a total of approximately 1.70 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Stud Earring',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115880/17_ej3xxw.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115874/18_xdy6cx.webp',
        'stone_by_color': 'Blue Sapphire',
        'price': 3800,
        'description': '12 pear-shaped sapphires weighing a total of approximately 2.10 carats and 2 round brilliant diamonds weighing a total of approximately 0.07 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Drop Earring',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115876/25_ohyxwk.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115879/26_ncvot1.webp',
        'stone_by_color': 'Pink Sapphire',
        'price': 4800,
        'description': '28 pear-shaped and round brilliant pink sapphires weighing a total of approximately 3.20 carats and 28 marquise and round brilliant diamonds weighing a total of approximately 1.98 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Drop Earring',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115873/23_xi7kdz.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115876/24_mlbxu2.webp',
        'stone_by_color': 'Blue Sapphire',
        'price': 4800,
        'description': '28 pear-shaped and round brilliant sapphires weighing a total of approximately 3.00 carats and 28 marquise and round brilliant diamonds weighing a total of approximately 1.98 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Drop Earring',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115880/21_sspkef.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115873/22_u9duuz.webp',
        'stone_by_color': 'White Diamond',
        'price': 5100,
        'description': 'A medley of marquise, pear-shaped, and round brilliant diamonds, weighing a total of approximately 4.38 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115871/7_bxav8b.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115882/8_udhrsq.avif',
        'stone_by_color': 'Pink Sapphire',
        'price': 6700,
        'description': '6 pear-shaped pink sapphires weighing a total of approximately 1.44 carats and 1 round brilliant diamond weighing approximately 0.04 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115871/5_tstc0a.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115874/6_yegbsi.avif',
        'stone_by_color': 'Blue Sapphire',
        'price': 6700,
        'description': '6 pear-shaped sapphires weighing a total of approximately 1.41 carats and 1 round brilliant diamond weighing approximately 0.04 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115876/3_ovmsps.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115874/4_gyndsx.webp',
        'stone_by_color': 'White Diamond',
        'price': 7000,
        'description': '6 pear-shaped and 1 round brilliant diamond weighing a total of approximately 1.07 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115877/1_20.58.26_rzrysl.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115877/2_20.58.26_zij1ov.avif',
        'stone_by_color': 'Red Ruby',
        'price': 6800,
        'description': '6 pear-shaped rubies weighing a total of approximately 1.68 carats and 1 round brilliant diamond weighing a total of approximately 0.04 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Necklace',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115874/33_ctp104.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115874/34_chlsa5.webp',
        'stone_by_color': 'Pink Sapphire',
        'price': 8400,
        'description': '78 pear-shaped and round brilliant pink sapphires weighing a total of approximately 8.61 carats and 99 marquise and round brilliant diamonds weighing a total of approximately 8.60 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Necklace',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115876/31_qt3bmf.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115879/32_odt4pf.avif',
        'stone_by_color': 'Blue Sapphire',
        'price': 8400,
        'description': '78 pear-shaped and round brilliant sapphires weighing a total of approximately 8.61 carats and 99 marquise and round brilliant diamonds weighing a total of approximately 8.37 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Necklace',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115877/29_hxlfiw.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115879/30_wyt89z.webp',
        'stone_by_color': 'White Diamond',
        'price': 8700,
        'description': '177 pear-shaped, marquise, and round brilliant diamonds, weighing a total of approximately 15.35 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Necklace',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115876/27_mz3g3o.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115879/28_ecki0c.avif',
        'stone_by_color': 'Red Ruby',
        'price': 8500,
        'description': '78 pear-shaped and round rubies weighing a total of approximately 9.13 carats and 99 marquise and round brilliant diamonds weighing a total of approximately 8.51 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Ring',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115876/13_jvc89m.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115883/14_ryucup.avif',
        'stone_by_color': 'Pink Sapphire',
        'price': 4400,
        'description': '6 pear-shaped pink sapphires weighing a total of approximately 2.22 carats and 1 round brilliant diamond weighing approximately 0.05 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Ring',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115876/11_kmd9oy.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115879/12_khumxz.avif',
        'stone_by_color': 'Blue Sapphire',
        'price': 4400,
        'description': '6 pear-shaped sapphires weighing a total of approximately 2.15 carats and 1 round brilliant diamond weighing approximately 0.05 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Ring',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115873/9_pfybkq.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115878/10_fcq7yp.webp',
        'stone_by_color': 'White Diamond',
        'price': 4600,
        'description': '6 pear-shaped and 1 round brilliant diamond, weighing a total of approximately 1.66 carats, set in platinum.',
        'target_gender': 'F',
    },
    # GERBERA
    {
        'category': 'Bracelet',
        'collection': 'Gerbera',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115898/7_dyy0ui.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115903/8_nb7rfa.avif',
        'stone_by_color': 'White Diamond',
        'price': 3400,
        'description': '29 round brilliant diamonds weighing a total of approximately 0.29 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Bracelet',
        'collection': 'Gerbera',
        'material': 'Rose Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115897/11_fnhj5z.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115897/12_c4gztu.avif',
        'stone_by_color': 'White Diamond',
        'price': 3200,
        'description': '29 round brilliant diamonds weighing a total of approximately 0.29 carats, set in 18K rose gold.',
        'target_gender': 'F',
    },
    {
        'category': 'Bracelet',
        'collection': 'Gerbera',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115890/9_hgiify.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115892/10_lbk6i1.avif',
        'stone_by_color': 'White Diamond',
        'price': 3200,
        'description': '29 round brilliant diamonds weighing a total of approximately 0.29 carats, set in 18K yellow gold.',
        'target_gender': 'F',
    },
    {
        'category': 'Earring',
        'collection': 'Gerbera',
        'material': 'Rose Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115890/23_riwfc0.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115892/24_sodzvz.webp',
        'stone_by_color': 'White Diamond',
        'price': 1600,
        'description': '58 round brilliant diamonds weighing a total of approximately 0.43 carats, set in 18K rose gold.',
        'target_gender': 'F',
    },
    {
        'category': 'Earring',
        'collection': 'Gerbera',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115898/21_o5ytzr.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115892/22_y8mhmh.webp',
        'stone_by_color': 'White Diamond',
        'price': 1600,
        'description': '58 round brilliant diamonds weighing a total of approximately 0.43 carats, set in 18K yellow gold.',
        'target_gender': 'F',
    },
    {
        'category': 'Earring',
        'collection': 'Gerbera',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115890/19_yq40yi.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115903/20_lsunqd.webp',
        'stone_by_color': 'White Diamond',
        'price': 1900,
        'description': '58 round brilliant diamonds weighing a total of approximately 0.43 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Gerbera',
        'material': 'Rose Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115898/5_ltcjn8.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115892/6_aj31h8.avif',
        'stone_by_color': 'White Diamond',
        'price': 2600,
        'description': '29 round brilliant diamonds weighing a total of approximately 0.29 carats, set in 18K rose gold.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Gerbera',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115893/3_nfudoh.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115904/4_jgqw79.avif',
        'stone_by_color': 'White Diamond',
        'price': 2600,
        'description': '29 round brilliant diamonds weighing a total of approximately 0.29 carats, set in 18K yellow gold.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Gerbera',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115892/1_mxaw0n.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115897/2_jbpdul.avif',
        'stone_by_color': 'White Diamond',
        'price': 2900,
        'description': '29 round brilliant diamonds weighing a total of approximately 0.29 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Ring',
        'collection': 'Gerbera',
        'material': 'Rose Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115898/17_sve1ov.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115892/18_mk2aen.webp',
        'stone_by_color': 'White Diamond',
        'price': 1900,
        'description': '31 round brilliant diamonds weighing a total of approximately 0.40 carats, set in 18K rose gold.',
        'target_gender': 'F',
    },
    {
        'category': 'Ring',
        'collection': 'Gerbera',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115889/15_vhtm13.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115904/16_oungz5.webp',
        'stone_by_color': 'White Diamond',
        'price': 1900,
        'description': '31 round brilliant diamonds weighinga total of approximately 0.40 carats, set in 18K yellow gold.',
        'target_gender': 'F',
    },
    {
        'category': 'Ring',
        'collection': 'Gerbera',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115892/13_c91ddg.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115892/14_khi7ft.webp',
        'stone_by_color': 'White Diamond',
        'price': 2100,
        'description': '31 round brilliant diamonds weighing a total of approximately 0.40 carats, set in platinum.',
        'target_gender': 'F',
    },
    # LEAF
    {
        'category': 'Pendant',
        'collection': 'Leaf',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115848/3_eqrpuo.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115848/4_zdqfzb.avif',
        'stone_by_color': 'White Diamond',
        'price': 3300,
        'description': '37 round brilliant diamonds weighing a total of approximately 0.19 carats, set in 18K yellow gold.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Leaf',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115848/1_y1wtvj.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115847/2_csala1.avif',
        'stone_by_color': 'White Diamond',
        'price': 3500,
        'description': '37 round brilliant diamonds weighing a total of approximately 0.19 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Necklace',
        'collection': 'Lilium',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115848/9_cglk2f.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115849/10_yaxfhs.webp',
        'stone_by_color': 'White Diamond',
        'price': 4300,
        'description': '619 round brilliant diamonds weighing a total of approximately 5.33 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Necklace',
        'collection': 'Lilium',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115848/11_mvguf6.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115848/12_vv0hw2.avif',
        'stone_by_color': 'White Diamond',
        'price': 4100,
        'description': '619 round brilliant diamonds weighing a total of approximately 5.33 carats, set in 18K yellow gold.',
        'target_gender': 'F',
    },
    {
        'category': 'Ring',
        'collection': 'Leaf',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115847/5_mbpwau.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115849/6_tma5f6.webp',
        'stone_by_color': 'White Diamond',
        'price': 2700,
        'description': '37 round brilliant diamonds weighing a total of approximately 0.18 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Ring',
        'collection': 'Leaf',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115848/7_u3mjub.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115848/8_admfwl.avif',
        'stone_by_color': 'White Diamond',
        'price': 2400,
        'description': '37 round brilliant diamonds weighing a total of approximately 0.18 carats, set in 18K yellow gold.',
        'target_gender': 'F',
    },
    # LILY
    {
        'category': 'Bracelet',
        'collection': 'Lily',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115861/3_z0khec.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115862/4_yomnun.avif',
        'stone_by_color': 'White Diamond',
        'price': 2900,
        'description': '75 round brilliant diamonds set in warm 18k yellow gold, this timeless piece captures one of nature’s most beautiful blooms.',
        'target_gender': 'F',
    },
    {
        'category': 'Bracelet',
        'collection': 'Lily',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115861/1_ra0at7.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115862/2_qtaybi.avif',
        'stone_by_color': 'White Diamond',
        'price': 3100,
        'description': '75 round brilliant diamonds, each masterfully set in lustrous platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Lily',
        'material': 'Rose Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115856/7_kkhuqt.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115862/8_fn8lmj.avif',
        'stone_by_color': 'White Diamond',
        'price': 4000,
        'description': '1 marquise and 45 round brilliant diamonds weighing a total of approximately 0.68 carats, set in 18K rose gold.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Lily',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115862/5_jg8e9x.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115861/6_viukk8.avif',
        'stone_by_color': 'White Diamond',
        'price': 4000,
        'description': '1 marquise and 45 round brilliant diamonds weighing a total of approximately 0.68 carats, set in 18K yellow gold.',
        'target_gender': 'F',
    },
    {
        'category': 'Ring',
        'collection': 'Lily',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115862/9_ug9qjk.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115861/10_kvifdt.avif',
        'stone_by_color': 'White Diamond',
        'price': 2400,
        'description': '1 marquise and 54 round brilliant diamonds weighing a total of approximately 0.41 carats, set in 18k yellow gold.',
        'target_gender': 'F',
    },
    ## !!!!!!!!!!!!!!!
    {
        'category': 'Ring',
        'collection': 'Lily',
        'material': 'Rose Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115861/11_qwmmry.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115861/12_wykwod.avif',
        'stone_by_color': 'White Diamond',
        'price': 2400,
        'description': '1 marquise and 54 round brilliant diamonds weighing a total of approximately 0.41 carats, set in 18K rose gold.',
        'target_gender': 'F',
    },
    # Lily of the Valley
    {
        'category': 'Drop Earring',
        'collection': 'Lily of the Valley',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115885/9_nrvzgx.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115886/10_gbgzq4.webp',
        'stone_by_color': 'White Diamond',
        'price': 7500,
        'description': '16 round brilliant and 4 pear-shaped diamonds weighing a total of 4.27 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Drop Earring',
        'collection': 'Lily of the Valley',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115886/1_zaesmv.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115886/2_omxh92.webp',
        'stone_by_color': 'Blue Aquamarine',
        'price': 7000,
        'description': '2 round and 2 pear-shaped sapphires weighing a total of approximately 1.90 carats, 4 round aquamarines weighing a total of approximately 1.00 carat, and 12 round brilliant and pear-shaped diamonds weighing a total of approximately 1.79 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Drop',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115884/5_azojfd.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115889/6_xefvoj.webp',
        'stone_by_color': 'Blue Aquamarine',
        'price': 7100,
        'description': '2 round sapphires weighing a total of approximately 0.98 carats, 1 round and 1 pear-shaped aquamarine weighing a total of approximately 0.23 carats, and 7 round brilliant and pear-shaped diamonds weighing a total of approximately 1.20 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Drop',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115889/14_rmtgtc.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115884/15_gbcgxu.webp',
        'stone_by_color': 'White Diamond',
        'price': 7900,
        'description': '9 round brilliant and 2 pear-shaped diamonds weighing a total of approximately 2.28 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Necklace',
        'collection': 'Lily of the Valley',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115889/16_ghdpy4.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115889/17_pzsxrr.webp',
        'stone_by_color': 'White Diamond',
        'price': 9100,
        'description': '148 round brilliant and 3 pear-shaped diamonds weighing a total of approximately 15.18 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Necklace',
        'collection': 'Lily of the Valley',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115889/7_mflsat.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115889/8_z0yovn.avif',
        'stone_by_color': 'Blue Aquamarine',
        'price': 8800,
        'description': '25 round and pear-shaped sapphires weighing a total of approximately 4.45 carats, 23 round aquamarines weighing a total of approximately 2.80 carats, and 130 round brilliant and pear-shaped diamonds weighing a total of approximately 8.73 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Ring',
        'collection': 'Lily of the Valley',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115886/3_onvsdq.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115885/4_k2z9sm.webp',
        'stone_by_color': 'Blue Aquamarine',
        'price': 6900,
        'description': '1 pear-shaped and 2 round sapphires weighing a total of approximately 1.08 carats, 2 round aquamarines weighing a total of approximately 0.38 carats, and 7 round brilliant and pear-shaped diamonds weighing a total of approximately 1.19 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Ring',
        'collection': 'Lily of the Valley',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115885/11_gxtusc.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115886/12_cyplba.webp',
        'stone_by_color': 'White Diamond',
        'price': 7300,
        'description': '10 round brilliant and 2 pear-shaped diamonds weighing a total of approximately 2.34 carats, set in platinum.',
        'target_gender': 'F',
    },
    # LOTUS
    {
        'category': 'Stud Earring',
        'collection': 'Lotus',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115849/5_akqszw.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115855/6_p1hv03.webp',
        'stone_by_color': 'Green Emerald',
        'price': 4200,
        'description': '6 marquise and pear-shaped emeralds weighing a total of approximately 2.65 carats and 8 marquise and pear-shaped diamonds weighing a total of approximately 2.88 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Stud Earring',
        'collection': 'Lotus',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115854/3_pwfqbd.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115855/4_zvx63m.avif',
        'stone_by_color': 'Blue Sapphire',
        'price': 4400,
        'description': '6 marquise and pear-shaped sapphires weighing a total of approximately 3.20 carats and 8 marquise and pear-shaped diamonds weighing a total of approximately 2.88 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Stud Earring',
        'collection': 'Lotus',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115854/1_dthftn.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115850/2_no2d0x.webp',
        'stone_by_color': 'Red Ruby',
        'price': 6600,
        'description': '6 marquise and pear-shaped rubies weighing a total of approximately 3.50 carats and 8 marquise and pear-shaped diamonds weighing a total of approximately 2.92 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Lotus',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115849/9_elxmpl.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115850/10_v5sj9r.avif',
        'stone_by_color': 'Red Ruby',
        'price': 7600,
        'description': '3 marquise and pear-shaped rubies weighing a total of approximately 2.50 carats and 4 marquise and pear-shaped diamonds weighing a total of approximately 2.21 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Lotus',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115849/7_kfghke.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115855/8_w3dnks.avif',
        'stone_by_color': 'Pink Sapphire',
        'price': 7400,
        'description': '3 marquise and pear-shaped pink sapphires weighing a total of approximately 2.61 carats and 2 pear-shaped and 2 marquise diamonds weighing a total of approximately 2.28 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Lotus',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115854/13_shljw5.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115855/14_yj8tc1.avif',
        'stone_by_color': 'Green Emerald',
        'price': 7200,
        'description': '3 marquise and pear-shaped emeralds weighing a total of approximately 2.00 carats and 4 marquise and pear-shaped diamonds weighing a total of approximately 2.15 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Lotus',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115854/11_grxxeo.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115854/12_qty9ix.avif',
        'stone_by_color': 'Blue Sapphire',
        'price': 7400,
        'description': '3 marquise and pear-shaped sapphires weighing a total of 2.50 carats and 4 marquise and pear-shaped diamonds weighing a total of approximately 2.15 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Ring',
        'collection': 'Lotus',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115855/17_txm6ur.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115849/18_othoqv.webp',
        'stone_by_color': 'Blue Sapphire',
        'price': 5200,
        'description': '3 marquise and pear-shaped sapphires weighing a total of approximately 2.81 carats and 4 marquise and pear-shaped diamonds weighing a total of approximately 2.10 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Ring',
        'collection': 'Lotus',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115855/15_jxzwza.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115850/16_fmv4dv.avif',
        'stone_by_color': 'Red Ruby',
        'price': 5400,
        'description': '3 marquise and pear-shaped rubies weighing a total of approximately 2.41 carats and 4 marquise and pear-shaped diamonds weighing a total of approximately 2.10 carats, set in platinum.',
        'target_gender': 'F',
    },
    # SUNFLOWER
    {
        'category': 'Stud Earring',
        'collection': 'Sunflower',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115904/9_sqhg38.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115904/10_iv9a0s.avif',
        'stone_by_color': 'Red Ruby',
        'price': 2100,
        'description': '16 round brilliant diamonds weighing a total of approximately 0.90 carats with round ruby center stones of approximately 0.44 carats each, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Stud Earring',
        'collection': 'Sunflower',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115907/7_biz36z.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115904/8_bnvuri.webp',
        'stone_by_color': 'Blue Sapphire',
        'price': 1900,
        'description': '16 round brilliant diamonds weighing a total of approximately 0.90 carats with round sapphire center stones of approximately 0.44 carats each, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Stud Earring',
        'collection': 'Sunflower',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115904/5_tdbnmb.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115907/6_hqhraj.webp',
        'stone_by_color': 'White Diamond',
        'price': 2200,
        'description': '18 round brilliant diamonds weighing a total of approximately 1.60 carats, center stones are approximately 0.30 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Ring',
        'collection': 'Sunflower',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115907/13_b96r6b.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115907/14_upeut9.avif',
        'stone_by_color': 'Red Ruby',
        'price': 3300,
        'description': '18 round brilliant diamonds, weighing a total of approximately 0.58 carats with a round ruby center stone of approximately 0.44 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Ring',
        'collection': 'Sunflower',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115904/11_gzogqa.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115907/12_lxtshr.avif',
        'stone_by_color': 'Blue Sapphire',
        'price': 3100,
        'description': '18 round brilliant diamonds, weighing a total of approximately 0.58 carats with a round sapphire center stone of approximately 0.44 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Bracelet',
        'collection': 'Sunflower',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756842745/sunflower1_wyf2ia.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756842745/sunflower2_uwzkkt.webp',
        'stone_by_color': 'Green Emerald',
        'price': 5200,
        'description': 'Elegantly wrapping the wrist, this bracelet`s delicate size celebrates the enduring beauty of flowers and incredible gemstones.',
        'target_gender': 'F',
    },
    {
        'category': 'Ring',
        'collection': 'Sunflower',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756843776/sunflower3_pn9b5h.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756843776/sunflower4_hk6afl.avif',
        'stone_by_color': 'Green Emerald',
        'price': 3900,
        'description': 'Inspired by the graceful geometry of a sunflower, this fashion ring features an emerald center stone and 18 sparkling diamonds. A bold, yet elegant statement piece, it brings nature`s beauty to the hand.',
        'target_gender': 'F',
    },
    {
        'category': 'Necklace',
        'collection': 'Sunflower',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756896009/sunflower5_ly6z6l.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756896010/sunflower6_iezpau.png',
        'stone_by_color': 'Green Emerald',
        'price': 10200,
        'description': 'This stunning necklace encompasses the neck with the radiant glow of a sunflower in full bloom. Featuring a harmonious composition of emeralds and round brilliant diamonds, this necklace celebrates the enduring beauty of nature`s greatest gifts.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Sunflower',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756896218/sunflower7_hhqzxo.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756896219/sunflower8_plmnw7.avif',
        'stone_by_color': 'Green Emerald',
        'price': 6100,
        'description': 'This pendant unites a vibrant round emerald with eight radiant round brilliant diamonds set in platinum. Inspired by the symmetry and spirit of sunflowers, it brings a burst of color and natural elegance to the neckline—perfectly suited for effortless wear from day to night.',
        'target_gender': 'F',
    },
    {
        'category': 'Stud Earring',
        'collection': 'Sunflower',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756896379/sunflower9_b6u96k.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756896379/sunflower10_rqzfli.avif',
        'stone_by_color': 'Green Emerald',
        'price': 2900,
        'description': 'A pair of beautiful earrings that delicately accent the ear, with an emerald green center stone accented by round brilliant diamonds. Recalling a sunflower in full bloom, these earrings make a statement for any occasion - day or night.',
        'target_gender': 'F',
    },
    # Daisy
    {
        'category': 'Stud Earring',
        'collection': 'Daisy',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121005/9_sciejy.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121016/10_darmna.webp',
        'stone_by_color': 'Pink Sapphire',
        'price': 1500,
        'description': '8 pear-shaped pink sapphires weighing a total of approximately 1.61 carats and 58 round brilliant diamonds weighing a total of approximately 2.66 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Stud Earring',
        'collection': 'Daisy',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121145/7_nvuh9g.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121006/8_bhttl1.webp',
        'stone_by_color': 'Red Ruby',
        'price': 1700,
        'description': '8 pear-shaped rubies weighing a total of approximately 1.83 carats and 58 round brilliant diamonds weighing a total of approximately 2.66 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Stud Earring',
        'collection': 'Daisy',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121009/13_mjvoux.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121008/14_rvbedu.webp',
        'stone_by_color': 'Yellow Sapphire',
        'price': 1500,
        'description': '8 pear-shaped yellow sapphires weighing a total of approximately 1.66 carats and 58 round brilliant diamonds weighing a total of approximately 2.66 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Stud Earring',
        'collection': 'Daisy',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121010/11_momftr.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121013/12_ou80ul.webp',
        'stone_by_color': 'Blue Aquamarine',
        'price': 1500,
        'description': '8 pear-shaped aquamarines weighing a total of approximately 1.21 carats and 58 round brilliant diamonds weighing a total of approximately 2.66 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Daisy',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121005/5_mvon0h.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121006/6_hr6odl.avif',
        'stone_by_color': 'Yellow Sapphire',
        'price': 4400,
        'description': '4 pear-shaped yellow sapphires weighing a total of approximately 0.85 carats and 29 round brilliant diamonds weighing a total of approximately 1.33 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Daisy',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121011/3_uskksz.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121262/4_cetexv.avif',
        'stone_by_color': 'Blue Aquamarine',
        'price': 4400,
        'description': '4 pear-shaped aquamarines weighing a total of approximately 0.60 carats and 29 round brilliant diamonds weighing a total of approximately 1.33 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Daisy',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121014/1_hgm4vf.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121261/2_t5lujx.avif',
        'stone_by_color': 'Pink Sapphire',
        'price': 4400,
        'description': '4 pear-shaped pink sapphires weighing a total of approximately 0.77 carats and 29 round brilliant diamonds weighing a total of approximately 1.33 carats, set in platinum.',
        'target_gender': 'F',
    },
    # Braceletes
    {
        'category': 'Watch',
        'collection': 'Bracelet',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746196508/1_cviir7.png',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746196508/2_kb2pnx.png',
        'stone_by_color': 'Green Emerald',
        'price': 14100,
        'description': 'Adorned with intense green tones, diamonds and mother-of-pearl.',
        'target_gender': 'F',
    },
    {
        'category': 'Watch',
        'collection': 'Bracelet',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746196509/1_cveecw.png',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746196509/2_jnlzu9.png',
        'stone_by_color': 'Red Ruby',
        'price': 14500,
        'description': 'Adorned with intense red tones, diamonds and mother-of-pearl.',
        'target_gender': 'F',
    },
    {
        'category': 'Watch',
        'collection': 'Bracelet',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746196508/1_zaou5v.png',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746196508/2_xadphd.png',
        'stone_by_color': 'Pink Sapphire',
        'price': 14900,
        'description': 'Adorned with soft pink tones, diamonds and mother-of-pearl.',
        'target_gender': 'F',
    },
    {
        'category': 'Watch',
        'collection': 'Bracelet',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746196508/1_sgyfdp.png',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746196508/2_zpbdin.png',
        'stone_by_color': 'Blue Aquamarine',
        'price': 14900,
        'description': 'Adorned with soft blue tones, diamonds and mother-of-pearl.',
        'target_gender': 'F',
    },
    {
        'category': 'Watch',
        'collection': 'Bracelet',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756919057/11_ymalof.png',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756919035/12_zsi7f7.png',
        'stone_by_color': 'White Diamond',
        'price': 14900,
        'description': 'Adorned with diamonds and mother-of-pearl.',
        'target_gender': 'F',
    },
    # Classics
    {
        'category': 'Watch',
        'collection': 'Classics',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746196509/1_ohgirz.png',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746196509/2_v3q4n1.png',
        'stone_by_color': 'Green Emerald',
        'price': 16200,
        'description': 'Adorned with intense green tones, diamonds and mother-of-pearl.',
        'target_gender': 'F',
    },
    {
        'category': 'Watch',
        'collection': 'Classics',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746196512/1_uesg5z.png',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746196511/2_agllhx.png',
        'stone_by_color': 'Red Ruby',
        'price': 17300,
        'description': 'Adorned with intense red tones, diamonds and mother-of-pearl.',
        'target_gender': 'F',
    },
    {
        'category': 'Watch',
        'collection': 'Classics',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746196510/1_vh9sj4.png',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746196510/2_nmhjr2.png',
        'stone_by_color': 'Blue Aquamarine',
        'price': 16100,
        'description': 'Adorned with soft blue tones, diamonds and mother-of-pearl.',
        'target_gender': 'F',
    },
    {
        'category': 'Watch',
        'collection': 'Classics',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746196509/1_yicqjg.png',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746196509/2_mdolsb.png',
        'stone_by_color': 'Pink Sapphire',
        'price': 16100,
        'description': 'Adorned with soft pink tones, diamonds and mother-of-pearl.',
        'target_gender': 'F',
    },

    # Men
    {
        'category': 'Watch',
        'collection': 'Classics',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756919198/1_kcop9l.png',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756919209/2_wawp9t.png',
        'stone_by_color': 'Green Emerald',
        'price': 22300,
        'description': 'Embellished with a vibrantly colored mother-of-pearl dial and a refreshing splash of gemstones.',
        'target_gender': 'M',
    },
    {
        'category': 'Watch',
        'collection': 'Classics',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756919198/3_nj90jc.png',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756919205/4_pxbmxx.png',
        'stone_by_color': 'White Diamond',
        'price': 21700,
        'description': 'Embellished with a vibrantly colored mother-of-pearl dial and a refreshing splash of gemstones.',
        'target_gender': 'M',
    },
    {
        'category': 'Watch',
        'collection': 'Classics',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756919034/5_y2tyr9.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756919195/6_kjumbc.png',
        'stone_by_color': 'White Diamond',
        'price': 21200,
        'description': 'Embellished with black onxy and sparkling diamonds.',
        'target_gender': 'M',
    },
    {
        'category': 'Watch',
        'collection': 'Classics',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756919187/7_nxrjxt.png',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756919200/8_wzpnjo.png',
        'stone_by_color': 'White Diamond',
        'price': 21200,
        'description': 'Embellished with a vibrantly colored mother-of-pearl dial and diamonds.',
        'target_gender': 'M',
    },

]
