products_data = [
    # BERRY
    {
        'category': 'Earring',
        'collection': 'Berry',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115862/9_zuupv7.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115868/10_ccqces.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999218/1_pfucbs.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999227/2_xpwcdf.png',
        'stone_by_color': 'Blue Sapphire',
        'price': 3600,
        'description': '16 round brilliant diamonds weighing a total of approximately 0.90 carats with round sapphire center stones of approximately 0.44 carats each, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Earring',
        'collection': 'Berry',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115870/7_oxmuys.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115867/8_k1zqeq.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999302/3_xwk7lb.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999303/4_qrijtq.png',
        'stone_by_color': 'Red Ruby',
        'price': 3700,
        'description': '16 round brilliant diamonds weighing a total of approximately 0.90 carats with round ruby center stones of approximately 0.44 carats each, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Earring',
        'collection': 'Berry',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115868/11_ntbstg.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115867/12_re58tf.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999343/5_mqg7gp.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999344/6_ovuyxh.png',
        'stone_by_color': 'Green Emerald',
        'price': 3400,
        'description': '10 pear-shaped diamonds weighing a total of approximately 3.35 carats with 6 round emeralds weighing a total of approximately 2.01 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Berry',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115862/5_rlufar.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115867/6_cb1tab.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999371/8_chnceo.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999370/7_zkigkm.png',
        'stone_by_color': 'Green Emerald',
        'price': 4400,
        'description': '5 pear-shaped diamonds weighing a total of approximately 2.01 carats with 3 round emeralds weighing a total of approximately 1.39 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Berry',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115867/3_bhkuqr.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115870/4_pbumhb.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999406/9_uiea8o.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999407/10_ktyhge.png',
        'stone_by_color': 'Blue Sapphire',
        'price': 4600,
        'description': '5 pear-shaped diamonds weighing a total of approximately 2.03 carats with 3 round sapphires weighing a total of approximately 1.86 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Berry',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115868/1_rcfsir.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115870/2_vf7yxw.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999435/11_nyh4zn.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999434/12_oe8zz4.png',
        'stone_by_color': 'Red Ruby',
        'price': 4800,
        'description': '5 pear-shaped diamonds weighing a total of approximately 2.03 carats with 3 round rubies weighing a total of approximately 1.88 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Ring',
        'collection': 'Berry',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115867/16_rkceku.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115868/15.avif_fmwmjz.png',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999465/13_wtvvlm.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999466/14_p0w173.png',
        'stone_by_color': 'Red Ruby',
        'price': 2800,
        'description': '13 round brilliant diamonds weighing a total of approximately 0.64 carats with 13 round rubies weighing a total of approximately 0.81 carats, prong-set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Ring',
        'collection': 'Berry',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115867/14_jaiuit.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115870/13.avif_hc7tnh.png',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999502/15_qw1qjv.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999503/16_t8nnpy.png',
        'stone_by_color': 'Blue Sapphire',
        'price': 2600,
        'description': '13 round brilliant diamonds weighing a total of approximately 0.64 carats with 13 round sapphires weighing a total of approximately 0.81 carats, prong-set in platinum.',
        'target_gender': 'F',
    },
    # FORGET ME NOT
    {
        'category': 'Bracelet',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115880/37_yydycy.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115884/38_ebclnr.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999528/17_c46b2w.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999528/18_zagfeq.png',
        'stone_by_color': 'Blue Sapphire',
        'price': 5200,
        'description': '45 pear-shaped and round brilliant sapphires weighing a total of approximately 4.17 carats and 33 pear-shaped, marquise and round brilliant diamonds weighing a total of approximately 4.24 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Bracelet',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115880/35_tl8ef4.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115874/36_vypeqm.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999555/19_whgtyq.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999556/20_tlfzzw.png',
        'stone_by_color': 'Red Ruby',
        'price': 5400,
        'description': '45 pear-shaped and round rubies weighing a total of approximately 4.43 carats and 33 pear-shaped, marquise and round brilliant diamonds weighing a total of approximately 4.37 carats, set in platinum. ',
        'target_gender': 'F',
    },
    {
        'category': 'Bracelet',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115880/39_ec0wun.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115871/40_jh7chy.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999593/21_xylmsm.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999594/22_povdm3.png',
        'stone_by_color': 'Pink Sapphire',
        'price': 5100,
        'description': '45 pear-shaped and round brilliant pink sapphires weighing a total of approximately 4.36 carats and 33 pear-shaped, marquise and round brilliant diamonds weighing a total of approximately 4.24 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Earring',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115871/19_cp3mbf.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115883/20_iumckw.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999619/24_wcsu5h.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999618/23_bldvfs.png',
        'stone_by_color': 'Pink Sapphire',
        'price': 2800,
        'description': '12 pear-shaped pink sapphires weighing a total of approximately 2.20 carats and 2 round brilliant diamonds weighing a total of approximately 0.07 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Earring',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115870/15_wi6mrj.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115883/16_ujqqh5.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999649/25_e3ogj0.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999649/26_udfae8.png',
        'stone_by_color': 'White Diamond',
        'price': 4100,
        'description': '12 pear-shaped diamonds and 2 round brilliant diamonds weighing a total of approximately 1.70 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Earring',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115880/17_ej3xxw.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115874/18_xdy6cx.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999675/27_qntgde.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999676/28_v57kfh.png',
        'stone_by_color': 'Blue Sapphire',
        'price': 3800,
        'description': '12 pear-shaped sapphires weighing a total of approximately 2.10 carats and 2 round brilliant diamonds weighing a total of approximately 0.07 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115871/7_bxav8b.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115882/8_udhrsq.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999782/35_ydtlrg.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999783/36_frholk.png',
        'stone_by_color': 'Pink Sapphire',
        'price': 6700,
        'description': '6 pear-shaped pink sapphires weighing a total of approximately 1.44 carats and 1 round brilliant diamond weighing approximately 0.04 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115871/5_tstc0a.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115874/6_yegbsi.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999808/37_ht9t2g.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999808/38_wonrzb.png',
        'stone_by_color': 'Blue Sapphire',
        'price': 6700,
        'description': '6 pear-shaped sapphires weighing a total of approximately 1.41 carats and 1 round brilliant diamond weighing approximately 0.04 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115876/3_ovmsps.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115874/4_gyndsx.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999839/40_ozb2nr.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999837/39_y0kotd.png',
        'stone_by_color': 'White Diamond',
        'price': 7000,
        'description': '6 pear-shaped and 1 round brilliant diamond weighing a total of approximately 1.07 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115877/1_20.58.26_rzrysl.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115877/2_20.58.26_zij1ov.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999869/41_lacnea.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999871/42_udbhpc.png',
        'stone_by_color': 'Red Ruby',
        'price': 6800,
        'description': '6 pear-shaped rubies weighing a total of approximately 1.68 carats and 1 round brilliant diamond weighing a total of approximately 0.04 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Necklace',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115874/33_ctp104.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115874/34_chlsa5.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999895/43_kohaap.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999898/44_mhomxp.png',
        'stone_by_color': 'Pink Sapphire',
        'price': 8400,
        'description': '78 pear-shaped and round brilliant pink sapphires weighing a total of approximately 8.61 carats and 99 marquise and round brilliant diamonds weighing a total of approximately 8.60 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Necklace',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115876/31_qt3bmf.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115879/32_odt4pf.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999924/45_anusqr.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756999925/46_s81hnp.png',
        'stone_by_color': 'Blue Sapphire',
        'price': 8400,
        'description': '78 pear-shaped and round brilliant sapphires weighing a total of approximately 8.61 carats and 99 marquise and round brilliant diamonds weighing a total of approximately 8.37 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Necklace',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115877/29_hxlfiw.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115879/30_wyt89z.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757000080/47_od3n5r.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757000082/48_cy2dv3.png',
        'stone_by_color': 'White Diamond',
        'price': 8700,
        'description': '177 pear-shaped, marquise, and round brilliant diamonds, weighing a total of approximately 15.35 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Necklace',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115876/27_mz3g3o.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115879/28_ecki0c.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757000116/49_fvqcal.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757000118/50_b8qsvx.png',
        'stone_by_color': 'Red Ruby',
        'price': 8500,
        'description': '78 pear-shaped and round rubies weighing a total of approximately 9.13 carats and 99 marquise and round brilliant diamonds weighing a total of approximately 8.51 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Ring',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115876/13_jvc89m.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115883/14_ryucup.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757000143/51_u0j7z7.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757000318/52_bf6elp.png',
        'stone_by_color': 'Pink Sapphire',
        'price': 4400,
        'description': '6 pear-shaped pink sapphires weighing a total of approximately 2.22 carats and 1 round brilliant diamond weighing approximately 0.05 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Ring',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115876/11_kmd9oy.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115879/12_khumxz.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757000376/53_bvkf7q.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757000378/54_speiwj.png',
        'stone_by_color': 'Blue Sapphire',
        'price': 4400,
        'description': '6 pear-shaped sapphires weighing a total of approximately 2.15 carats and 1 round brilliant diamond weighing approximately 0.05 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Ring',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115873/9_pfybkq.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115878/10_fcq7yp.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757000402/55_vdcvhh.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757000404/56_b7tgqt.png',
        'stone_by_color': 'White Diamond',
        'price': 4600,
        'description': '6 pear-shaped and 1 round brilliant diamond, weighing a total of approximately 1.66 carats, set in platinum.',
        'target_gender': 'F',
    },
    # GERBERA
    {
        'category': 'Bracelet',
        'collection': 'Gerbera',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115898/7_dyy0ui.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115903/8_nb7rfa.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757000429/57_ntygdy.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757000432/58_djnwe9.png',
        'stone_by_color': 'White Diamond',
        'price': 3400,
        'description': '29 round brilliant diamonds weighing a total of approximately 0.29 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Bracelet',
        'collection': 'Gerbera',
        'material': 'Rose Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115897/11_fnhj5z.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115897/12_c4gztu.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757000456/59_uc9ubs.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757000458/60_fcu3bc.png',
        'stone_by_color': 'White Diamond',
        'price': 3200,
        'description': '29 round brilliant diamonds weighing a total of approximately 0.29 carats, set in 18K rose gold.',
        'target_gender': 'F',
    },
    {
        'category': 'Bracelet',
        'collection': 'Gerbera',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115890/9_hgiify.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115892/10_lbk6i1.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757000481/61_gqinup.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757000484/62_fsyj4c.png',
        'stone_by_color': 'White Diamond',
        'price': 3200,
        'description': '29 round brilliant diamonds weighing a total of approximately 0.29 carats, set in 18K yellow gold.',
        'target_gender': 'F',
    },
    {
        'category': 'Earring',
        'collection': 'Gerbera',
        'material': 'Rose Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115890/23_riwfc0.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115892/24_sodzvz.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757000515/63_lrmowh.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757000511/64_bouiuk.png',
        'stone_by_color': 'White Diamond',
        'price': 1600,
        'description': '58 round brilliant diamonds weighing a total of approximately 0.43 carats, set in 18K rose gold.',
        'target_gender': 'F',
    },
    {
        'category': 'Earring',
        'collection': 'Gerbera',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115898/21_o5ytzr.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115892/22_y8mhmh.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757000537/65_na8l5x.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757000542/66_dkq1m7.png',
        'stone_by_color': 'White Diamond',
        'price': 1600,
        'description': '58 round brilliant diamonds weighing a total of approximately 0.43 carats, set in 18K yellow gold.',
        'target_gender': 'F',
    },
    {
        'category': 'Earring',
        'collection': 'Gerbera',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115890/19_yq40yi.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115903/20_lsunqd.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757000564/67_fovyjo.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757000567/68_jun1ca.png',
        'stone_by_color': 'White Diamond',
        'price': 1900,
        'description': '58 round brilliant diamonds weighing a total of approximately 0.43 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Gerbera',
        'material': 'Rose Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115898/5_ltcjn8.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115892/6_aj31h8.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757000591/69_i1aywl.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757000595/70_sx61dv.png',
        'stone_by_color': 'White Diamond',
        'price': 2600,
        'description': '29 round brilliant diamonds weighing a total of approximately 0.29 carats, set in 18K rose gold.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Gerbera',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115893/3_nfudoh.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115904/4_jgqw79.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757000618/71_apfgel.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757000621/72_yqk8vt.png',
        'stone_by_color': 'White Diamond',
        'price': 2600,
        'description': '29 round brilliant diamonds weighing a total of approximately 0.29 carats, set in 18K yellow gold.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Gerbera',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115892/1_mxaw0n.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115897/2_jbpdul.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757000648/73_yuksnh.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757000652/74_bemglu.png',
        'stone_by_color': 'White Diamond',
        'price': 2900,
        'description': '29 round brilliant diamonds weighing a total of approximately 0.29 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Ring',
        'collection': 'Gerbera',
        'material': 'Rose Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115898/17_sve1ov.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115892/18_mk2aen.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757000679/75_s0xdqk.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757000683/76_fgwpqa.png',
        'stone_by_color': 'White Diamond',
        'price': 1900,
        'description': '31 round brilliant diamonds weighing a total of approximately 0.40 carats, set in 18K rose gold.',
        'target_gender': 'F',
    },
    {
        'category': 'Ring',
        'collection': 'Gerbera',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115889/15_vhtm13.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115904/16_oungz5.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757000709/77_dbpr1g.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757000709/78_tlhs0b.png',
        'stone_by_color': 'White Diamond',
        'price': 1900,
        'description': '31 round brilliant diamonds weighinga total of approximately 0.40 carats, set in 18K yellow gold.',
        'target_gender': 'F',
    },
    {
        'category': 'Ring',
        'collection': 'Gerbera',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115892/13_c91ddg.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115892/14_khi7ft.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757000735/79_zgaqks.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757000740/80_iwmerz.png',
        'stone_by_color': 'White Diamond',
        'price': 2100,
        'description': '31 round brilliant diamonds weighing a total of approximately 0.40 carats, set in platinum.',
        'target_gender': 'F',
    },
    # LEAF
    {
        'category': 'Pendant',
        'collection': 'Lily',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115848/3_eqrpuo.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115848/4_zdqfzb.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757000765/81_uqyw5g.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757000769/82_cr8aim.png',
        'stone_by_color': 'White Diamond',
        'price': 3300,
        'description': '37 round brilliant diamonds weighing a total of approximately 0.19 carats, set in 18K yellow gold.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Lily',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115848/1_y1wtvj.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115847/2_csala1.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757000799/83_dllgoc.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757001270/84_y5isbo.png',
        'stone_by_color': 'White Diamond',
        'price': 3500,
        'description': '37 round brilliant diamonds weighing a total of approximately 0.19 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Necklace',
        'collection': 'Lily',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115848/9_cglk2f.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115849/10_yaxfhs.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757000832/85_fmwlut.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757001270/86_slgr0s.png',
        'stone_by_color': 'White Diamond',
        'price': 4300,
        'description': '619 round brilliant diamonds weighing a total of approximately 5.33 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Necklace',
        'collection': 'Lily',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115848/11_mvguf6.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115848/12_vv0hw2.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757001371/87_xkhz1v.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757001372/88_jxyrvl.png',
        'stone_by_color': 'White Diamond',
        'price': 4100,
        'description': '619 round brilliant diamonds weighing a total of approximately 5.33 carats, set in 18K yellow gold.',
        'target_gender': 'F',
    },
    {
        'category': 'Ring',
        'collection': 'Lily',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115847/5_mbpwau.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115849/6_tma5f6.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757001398/89_tlablu.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757001399/90_xhrb1t.png',
        'stone_by_color': 'White Diamond',
        'price': 2700,
        'description': '37 round brilliant diamonds weighing a total of approximately 0.18 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Ring',
        'collection': 'Lily',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115848/7_u3mjub.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115848/8_admfwl.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757001423/91_jg4qnm.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757001424/92_mczbml.png',
        'stone_by_color': 'White Diamond',
        'price': 2400,
        'description': '37 round brilliant diamonds weighing a total of approximately 0.18 carats, set in 18K yellow gold.',
        'target_gender': 'F',
    },
    # LILY
    {
        'category': 'Bracelet',
        'collection': 'Lily',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115861/3_z0khec.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115862/4_yomnun.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757001447/93_wqbdqn.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757001450/94_i3mjzq.png',
        'stone_by_color': 'White Diamond',
        'price': 2900,
        'description': '75 round brilliant diamonds set in warm 18k yellow gold, this timeless piece captures one of nature’s most beautiful blooms.',
        'target_gender': 'F',
    },
    {
        'category': 'Bracelet',
        'collection': 'Lily',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115861/1_ra0at7.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115862/2_qtaybi.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757001476/95_ao2vlr.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757001476/96_e9jeav.png',
        'stone_by_color': 'White Diamond',
        'price': 3100,
        'description': '75 round brilliant diamonds, each masterfully set in lustrous platinum.',
        'target_gender': 'F',
    },
    # Drop
    {
        'category': 'Pendant',
        'collection': 'Drop',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115884/5_azojfd.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115889/6_xefvoj.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757001954/109_gdnflh.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002055/110_ucgjbz.png',
        'stone_by_color': 'Blue Aquamarine',
        'price': 7100,
        'description': '2 round sapphires weighing a total of approximately 0.98 carats, 1 round and 1 pear-shaped aquamarine weighing a total of approximately 0.23 carats, and 7 round brilliant and pear-shaped diamonds weighing a total of approximately 1.20 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Drop',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115889/14_rmtgtc.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115884/15_gbcgxu.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002102/111_nylnhw.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002252/112_hyn5zo.png',
        'stone_by_color': 'White Diamond',
        'price': 7900,
        'description': '9 round brilliant and 2 pear-shaped diamonds weighing a total of approximately 2.28 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Necklace',
        'collection': 'Drop',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115889/7_mflsat.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115889/8_z0yovn.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002313/115_nmkx77.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002313/116_hte7cm.png',
        'stone_by_color': 'Blue Aquamarine',
        'price': 8800,
        'description': '25 round and pear-shaped sapphires weighing a total of approximately 4.45 carats, 23 round aquamarines weighing a total of approximately 2.80 carats, and 130 round brilliant and pear-shaped diamonds weighing a total of approximately 8.73 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Ring',
        'collection': 'Drop',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115886/3_onvsdq.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115885/4_k2z9sm.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002349/117_kzs43h.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002350/118_htsvth.png',
        'stone_by_color': 'Blue Aquamarine',
        'price': 6900,
        'description': '1 pear-shaped and 2 round sapphires weighing a total of approximately 1.08 carats, 2 round aquamarines weighing a total of approximately 0.38 carats, and 7 round brilliant and pear-shaped diamonds weighing a total of approximately 1.19 carats, set in platinum.',
        'target_gender': 'F',
    },
    # LOTUS
    {
        'category': 'Earring',
        'collection': 'Lotus',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115849/5_akqszw.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115855/6_p1hv03.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002396/121_kfwcaq.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002397/122_jc1mfh.png',
        'stone_by_color': 'Green Emerald',
        'price': 4200,
        'description': '6 marquise and pear-shaped emeralds weighing a total of approximately 2.65 carats and 8 marquise and pear-shaped diamonds weighing a total of approximately 2.88 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Earring',
        'collection': 'Lotus',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115854/3_pwfqbd.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115855/4_zvx63m.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002420/123_onrq7l.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002421/124_y2p2sr.png',
        'stone_by_color': 'Blue Sapphire',
        'price': 4400,
        'description': '6 marquise and pear-shaped sapphires weighing a total of approximately 3.20 carats and 8 marquise and pear-shaped diamonds weighing a total of approximately 2.88 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Earring',
        'collection': 'Lotus',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115854/1_dthftn.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115850/2_no2d0x.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002453/125_mqntcg.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002450/126_zlk30o.png',
        'stone_by_color': 'Red Ruby',
        'price': 6600,
        'description': '6 marquise and pear-shaped rubies weighing a total of approximately 3.50 carats and 8 marquise and pear-shaped diamonds weighing a total of approximately 2.92 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Lotus',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115849/9_elxmpl.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115850/10_v5sj9r.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002474/127_mco2ou.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002560/128_rbejmw.png',
        'stone_by_color': 'Red Ruby',
        'price': 7600,
        'description': '3 marquise and pear-shaped rubies weighing a total of approximately 2.50 carats and 4 marquise and pear-shaped diamonds weighing a total of approximately 2.21 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Lotus',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115849/7_kfghke.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115855/8_w3dnks.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002632/129_okouku.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002636/130_pntjid.png',
        'stone_by_color': 'Pink Sapphire',
        'price': 7400,
        'description': '3 marquise and pear-shaped pink sapphires weighing a total of approximately 2.61 carats and 2 pear-shaped and 2 marquise diamonds weighing a total of approximately 2.28 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Lotus',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115854/13_shljw5.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115855/14_yj8tc1.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002657/131_h7wc2w.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002658/132_ogpib4.png',
        'stone_by_color': 'Green Emerald',
        'price': 7200,
        'description': '3 marquise and pear-shaped emeralds weighing a total of approximately 2.00 carats and 4 marquise and pear-shaped diamonds weighing a total of approximately 2.15 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Lotus',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115854/11_grxxeo.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115854/12_qty9ix.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002690/133_k1gaxl.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002690/134_r8m7rc.png',
        'stone_by_color': 'Blue Sapphire',
        'price': 7400,
        'description': '3 marquise and pear-shaped sapphires weighing a total of 2.50 carats and 4 marquise and pear-shaped diamonds weighing a total of approximately 2.15 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Ring',
        'collection': 'Lotus',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115855/17_txm6ur.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115849/18_othoqv.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002712/135_z3wdrm.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002713/136_lmyu4r.png',
        'stone_by_color': 'Blue Sapphire',
        'price': 5200,
        'description': '3 marquise and pear-shaped sapphires weighing a total of approximately 2.81 carats and 4 marquise and pear-shaped diamonds weighing a total of approximately 2.10 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Ring',
        'collection': 'Lotus',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115855/15_jxzwza.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115850/16_fmv4dv.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002736/137_zsqomh.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002736/138_tutgan.png',
        'stone_by_color': 'Red Ruby',
        'price': 5400,
        'description': '3 marquise and pear-shaped rubies weighing a total of approximately 2.41 carats and 4 marquise and pear-shaped diamonds weighing a total of approximately 2.10 carats, set in platinum.',
        'target_gender': 'F',
    },
    # SUNFLOWER
    {
        'category': 'Earring',
        'collection': 'Sunflower',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115904/9_sqhg38.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115904/10_iv9a0s.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002757/139_kil0me.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002758/140_e2lwna.png',
        'stone_by_color': 'Red Ruby',
        'price': 2100,
        'description': '16 round brilliant diamonds weighing a total of approximately 0.90 carats with round ruby center stones of approximately 0.44 carats each, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Earring',
        'collection': 'Sunflower',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115907/7_biz36z.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115904/8_bnvuri.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002783/141_klcyn8.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002783/142_q8rqd4.png',
        'stone_by_color': 'Blue Sapphire',
        'price': 1900,
        'description': '16 round brilliant diamonds weighing a total of approximately 0.90 carats with round sapphire center stones of approximately 0.44 carats each, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Earring',
        'collection': 'Sunflower',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115904/5_tdbnmb.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115907/6_hqhraj.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002807/143_tdolza.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002807/144_bycodn.png',
        'stone_by_color': 'White Diamond',
        'price': 2200,
        'description': '18 round brilliant diamonds weighing a total of approximately 1.60 carats, center stones are approximately 0.30 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Ring',
        'collection': 'Sunflower',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115907/13_b96r6b.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115907/14_upeut9.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002834/145_i5ogu5.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002835/146_jja0do.png',
        'stone_by_color': 'Red Ruby',
        'price': 3300,
        'description': '18 round brilliant diamonds, weighing a total of approximately 0.58 carats with a round ruby center stone of approximately 0.44 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Ring',
        'collection': 'Sunflower',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115904/11_gzogqa.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115907/12_lxtshr.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002860/147_ijqwid.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002860/148_zjkx4e.png',
        'stone_by_color': 'Blue Sapphire',
        'price': 3100,
        'description': '18 round brilliant diamonds, weighing a total of approximately 0.58 carats with a round sapphire center stone of approximately 0.44 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Bracelet',
        'collection': 'Sunflower',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756842745/sunflower1_wyf2ia.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756842745/sunflower2_uwzkkt.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002888/150_nhqev4.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002887/149_rjdc8v.png',
        'stone_by_color': 'Green Emerald',
        'price': 5200,
        'description': 'Elegantly wrapping the wrist, this bracelet`s delicate size celebrates the enduring beauty of flowers and incredible gemstones.',
        'target_gender': 'F',
    },
    {
        'category': 'Ring',
        'collection': 'Sunflower',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756843776/sunflower3_pn9b5h.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756843776/sunflower4_hk6afl.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002922/151_ykvdk8.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002923/152_ffol8f.png',
        'stone_by_color': 'Green Emerald',
        'price': 3900,
        'description': 'Inspired by the graceful geometry of a sunflower, this fashion ring features an emerald center stone and 18 sparkling diamonds. A bold, yet elegant statement piece, it brings nature`s beauty to the hand.',
        'target_gender': 'F',
    },
    {
        'category': 'Necklace',
        'collection': 'Sunflower',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756896009/sunflower5_ly6z6l.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756896010/sunflower6_iezpau.png',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002946/153_nhuxtc.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002946/154_xfk2ol.png',
        'stone_by_color': 'Green Emerald',
        'price': 10200,
        'description': 'This stunning necklace encompasses the neck with the radiant glow of a sunflower in full bloom. Featuring a harmonious composition of emeralds and round brilliant diamonds, this necklace celebrates the enduring beauty of nature`s greatest gifts.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Sunflower',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756896218/sunflower7_hhqzxo.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756896219/sunflower8_plmnw7.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002970/155_dymwyv.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757002971/156_kstixd.png',
        'stone_by_color': 'Green Emerald',
        'price': 6100,
        'description': 'This pendant unites a vibrant round emerald with eight radiant round brilliant diamonds set in platinum. Inspired by the symmetry and spirit of sunflowers, it brings a burst of color and natural elegance to the neckline—perfectly suited for effortless wear from day to night.',
        'target_gender': 'F',
    },
    {
        'category': 'Earring',
        'collection': 'Sunflower',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756896379/sunflower9_b6u96k.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756896379/sunflower10_rqzfli.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003000/157_g6xz13.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003001/158_b7rpga.png',
        'stone_by_color': 'Green Emerald',
        'price': 2900,
        'description': 'A pair of beautiful earrings that delicately accent the ear, with an emerald green center stone accented by round brilliant diamonds. Recalling a sunflower in full bloom, these earrings make a statement for any occasion - day or night.',
        'target_gender': 'F',
    },
    # Daisy
    {
        'category': 'Earring',
        'collection': 'Daisy',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121005/9_sciejy.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121016/10_darmna.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003019/159_zzghsm.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003020/160_sazqoz.png',
        'stone_by_color': 'Pink Sapphire',
        'price': 1500,
        'description': '8 pear-shaped pink sapphires weighing a total of approximately 1.61 carats and 58 round brilliant diamonds weighing a total of approximately 2.66 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Earring',
        'collection': 'Daisy',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121145/7_nvuh9g.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121006/8_bhttl1.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003041/161_ftza0l.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003043/162_os0d30.png',
        'stone_by_color': 'Red Ruby',
        'price': 1700,
        'description': '8 pear-shaped rubies weighing a total of approximately 1.83 carats and 58 round brilliant diamonds weighing a total of approximately 2.66 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Earring',
        'collection': 'Daisy',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121009/13_mjvoux.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121008/14_rvbedu.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003063/163_dynuk9.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003064/164_r5ppwj.png',
        'stone_by_color': 'Yellow Sapphire',
        'price': 1500,
        'description': '8 pear-shaped yellow sapphires weighing a total of approximately 1.66 carats and 58 round brilliant diamonds weighing a total of approximately 2.66 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Earring',
        'collection': 'Daisy',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121010/11_momftr.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121013/12_ou80ul.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003102/165_onc47f.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003103/166_z13fnz.png',
        'stone_by_color': 'Blue Aquamarine',
        'price': 1500,
        'description': '8 pear-shaped aquamarines weighing a total of approximately 1.21 carats and 58 round brilliant diamonds weighing a total of approximately 2.66 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Daisy',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121005/5_mvon0h.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121006/6_hr6odl.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003126/167_oe5jwo.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003127/168_zf1us0.png',
        'stone_by_color': 'Yellow Sapphire',
        'price': 4400,
        'description': '4 pear-shaped yellow sapphires weighing a total of approximately 0.85 carats and 29 round brilliant diamonds weighing a total of approximately 1.33 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Daisy',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121011/3_uskksz.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121262/4_cetexv.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003149/169_y2tr87.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003151/170_ecadeu.png',
        'stone_by_color': 'Blue Aquamarine',
        'price': 4400,
        'description': '4 pear-shaped aquamarines weighing a total of approximately 0.60 carats and 29 round brilliant diamonds weighing a total of approximately 1.33 carats, set in platinum.',
        'target_gender': 'F',
    },
    {
        'category': 'Pendant',
        'collection': 'Daisy',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121014/1_hgm4vf.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121261/2_t5lujx.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003172/171_tj1ru4.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003174/172_f5h0hq.png',
        'stone_by_color': 'Pink Sapphire',
        'price': 4400,
        'description': '4 pear-shaped pink sapphires weighing a total of approximately 0.77 carats and 29 round brilliant diamonds weighing a total of approximately 1.33 carats, set in platinum.',
        'target_gender': 'F',
    },
    # Braceletes
    {
        'category': 'Watch',
        'collection': 'Elegance',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746196508/1_cviir7.png',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746196508/2_kb2pnx.png',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003206/173_qx6lx4.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003210/174_paltxf.png',
        'stone_by_color': 'Green Emerald',
        'price': 14100,
        'description': 'Adorned with intense green tones, diamonds and mother-of-pearl.',
        'target_gender': 'F',
    },
    {
        'category': 'Watch',
        'collection': 'Elegance',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746196509/1_cveecw.png',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746196509/2_jnlzu9.png',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003286/175_bff7a1.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003286/176_h7c9yy.png',
        'stone_by_color': 'Red Ruby',
        'price': 14500,
        'description': 'Adorned with intense red tones, diamonds and mother-of-pearl.',
        'target_gender': 'F',
    },
    {
        'category': 'Watch',
        'collection': 'Elegance',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746196508/1_zaou5v.png',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746196508/2_xadphd.png',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003311/177_twxs7t.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003310/178_gq3fn4.png',
        'stone_by_color': 'Pink Sapphire',
        'price': 14900,
        'description': 'Adorned with soft pink tones, diamonds and mother-of-pearl.',
        'target_gender': 'F',
    },
    {
        'category': 'Watch',
        'collection': 'Elegance',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746196508/1_sgyfdp.png',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746196508/2_zpbdin.png',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003335/179_gnuwlj.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003335/180_ia4r2a.png',
        'stone_by_color': 'Blue Aquamarine',
        'price': 14900,
        'description': 'Adorned with soft blue tones, diamonds and mother-of-pearl.',
        'target_gender': 'F',
    },
    {
        'category': 'Watch',
        'collection': 'Elegance',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756919057/11_ymalof.png',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756919035/12_zsi7f7.png',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003356/181_zgsvid.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003359/182_w1htrx.png',
        'stone_by_color': 'White Diamond',
        'price': 14900,
        'description': 'Adorned with diamonds and mother-of-pearl.',
        'target_gender': 'F',
    },
    # Classics
    {
        'category': 'Watch',
        'collection': 'Classics',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746196509/1_ohgirz.png',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746196509/2_v3q4n1.png',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003378/183_an0tki.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003380/184_lwowna.png',
        'stone_by_color': 'Green Emerald',
        'price': 16200,
        'description': 'Adorned with intense green tones, diamonds and mother-of-pearl.',
        'target_gender': 'F',
    },
    {
        'category': 'Watch',
        'collection': 'Classics',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746196512/1_uesg5z.png',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746196511/2_agllhx.png',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003401/185_ko1mey.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003398/186_v3uoa9.png',
        'stone_by_color': 'Red Ruby',
        'price': 17300,
        'description': 'Adorned with intense red tones, diamonds and mother-of-pearl.',
        'target_gender': 'F',
    },
    {
        'category': 'Watch',
        'collection': 'Classics',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746196510/1_vh9sj4.png',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746196510/2_nmhjr2.png',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003420/187_hvu0te.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003421/188_mxclph.png',
        'stone_by_color': 'Blue Aquamarine',
        'price': 16100,
        'description': 'Adorned with soft blue tones, diamonds and mother-of-pearl.',
        'target_gender': 'F',
    },
    {
        'category': 'Watch',
        'collection': 'Classics',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746196509/1_yicqjg.png',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746196509/2_mdolsb.png',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003558/189_azxwny.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003532/190_z7tamj.png',
        'stone_by_color': 'Pink Sapphire',
        'price': 16100,
        'description': 'Adorned with soft pink tones, diamonds and mother-of-pearl.',
        'target_gender': 'F',
    },

    # Men
    {
        'category': 'Watch',
        'collection': 'Ocean',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756919198/1_kcop9l.png',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756919209/2_wawp9t.png',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003582/191_o0k7ff.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003583/192_yiwhjw.png',
        'stone_by_color': 'Green Emerald',
        'price': 21700,
        'description': 'Embellished with a vibrantly colored mother-of-pearl dial and a refreshing splash of gemstones, the watch features a green genuine leather strap.',
        'target_gender': 'M',
    },
    {
        'category': 'Watch',
        'collection': 'Ocean',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756919198/3_nj90jc.png',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756919205/4_pxbmxx.png',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003604/193_jwdvqv.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003606/194_ncdwhl.png',
        'stone_by_color': 'White Diamond',
        'price': 21700,
        'description': 'Embellished with a vibrantly colored mother-of-pearl dial and a refreshing splash of gemstones, the watch features a navy blue genuine leather strap.',
        'target_gender': 'M',
    },
    {
        'category': 'Watch',
        'collection': 'Ocean',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756919034/5_y2tyr9.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756919195/6_kjumbc.png',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003629/195_f9qcyk.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003631/196_yedbqv.png',
        'stone_by_color': 'White Diamond',
        'price': 21200,
        'description': 'Embellished with black onxy and sparkling diamonds, the watch features a black genuine leather strap.',
        'target_gender': 'M',
    },
    {
        'category': 'Watch',
        'collection': 'Midnight',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756919187/7_nxrjxt.png',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756919200/8_wzpnjo.png',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003662/197_wmsstn.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003664/198_ovbswh.png',
        'stone_by_color': 'White Diamond',
        'price': 21200,
        'description': 'Embellished with a vibrantly colored mother-of-pearl dial and diamonds, the watch features a brown genuine leather strap.',
        'target_gender': 'M',
    },
    {
        'category': 'Watch',
        'collection': 'Midnight',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756919034/9_rcckzc.png',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1756919204/10_vd3aql.png',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003747/199_bq85vu.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1757003748/200_vhdbbv.png',
        'stone_by_color': 'White Diamond',
        'price': 21200,
        'description': 'Embellished with a vibrantly colored mother-of-pearl dial and diamonds, the watch features a navy blue genuine leather strap.',
        'target_gender': 'M',
    },
]
