from src.chatbot.prompts.base import CRITICAL_RULES, CONTEXT, DO_NOT_RECOMMEND_PRODUCT, NEXT, ROLE_CONCISE, WHO_AM_I


SYSTEM_MESSAGE_COMPANY_INFORMATION_HANDLER = (
CONTEXT +
ROLE_CONCISE +
WHO_AM_I +
DO_NOT_RECOMMEND_PRODUCT +
CRITICAL_RULES +
NEXT 
)

HUMAN_MESSAGE_COMPANY_INFORMATION_HANDLER = (
"""
BASED ON:\n
1. CONVERSATION MEMORY:\n{conversation_memory}\n\n
2. CONTEXT:\n{context}\n\n
3. Respond to my STATEMENT:\n\n{customer_query}
"""
)