# Generated by Django 5.2 on 2025-04-15 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_image_url', models.URLField()),
                ('second_image_url', models.URLField()),
                ('category', models.CharField(choices=[('BR', 'Bracelet'), ('CH', 'Charm'), ('DE', 'Drop Earring'), ('NE', 'Necklace'), ('PE', 'Pendant'), ('RI', 'Ring'), ('SE', 'Stud Earring')], max_length=2)),
                ('color', models.CharField(choices=[('BL', 'Blue'), ('PI', 'Pink'), ('WH', 'White')], max_length=2)),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.description')),
            ],
        ),
    ]
