# Generated by Django 5.2 on 2025-04-06 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gemstone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('PS', 'Pink Sapphire'), ('BS', 'Blue Sapphire'), ('BD', 'Brilliant Diamond')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='DropEarring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_image_url', models.URLField()),
                ('second_image_url', models.URLField()),
                ('description', models.TextField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('size', models.DecimalField(decimal_places=2, max_digits=4)),
                ('gemstone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.gemstone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bracelet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_image_url', models.URLField()),
                ('second_image_url', models.URLField()),
                ('description', models.TextField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('size', models.CharField(max_length=1)),
                ('gemstone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.gemstone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Necklace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_image_url', models.URLField()),
                ('second_image_url', models.URLField()),
                ('description', models.TextField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('size', models.CharField(max_length=1)),
                ('gemstone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.gemstone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pendant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_image_url', models.URLField()),
                ('second_image_url', models.URLField()),
                ('description', models.TextField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('size', models.CharField(max_length=1)),
                ('gemstone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.gemstone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_image_url', models.URLField()),
                ('second_image_url', models.URLField()),
                ('description', models.TextField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('size', models.CharField(max_length=1)),
                ('gemstone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.gemstone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudEarring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_image_url', models.URLField()),
                ('second_image_url', models.URLField()),
                ('description', models.TextField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('size', models.DecimalField(decimal_places=2, max_digits=4)),
                ('gemstone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.gemstone')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
