# Generated by Django 5.2 on 2025-04-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracelet',
            name='gemstone',
            field=models.CharField(choices=[('PS', 'Pink Sapphire'), ('BS', 'Blue Sapphire'), ('BD', 'Brilliant Diamond')], max_length=2),
        ),
        migrations.AlterField(
            model_name='dropearring',
            name='gemstone',
            field=models.CharField(choices=[('PS', 'Pink Sapphire'), ('BS', 'Blue Sapphire'), ('BD', 'Brilliant Diamond')], max_length=2),
        ),
        migrations.AlterField(
            model_name='necklace',
            name='gemstone',
            field=models.CharField(choices=[('PS', 'Pink Sapphire'), ('BS', 'Blue Sapphire'), ('BD', 'Brilliant Diamond')], max_length=2),
        ),
        migrations.AlterField(
            model_name='pendant',
            name='gemstone',
            field=models.CharField(choices=[('PS', 'Pink Sapphire'), ('BS', 'Blue Sapphire'), ('BD', 'Brilliant Diamond')], max_length=2),
        ),
        migrations.AlterField(
            model_name='ring',
            name='gemstone',
            field=models.CharField(choices=[('PS', 'Pink Sapphire'), ('BS', 'Blue Sapphire'), ('BD', 'Brilliant Diamond')], max_length=2),
        ),
        migrations.AlterField(
            model_name='studearring',
            name='gemstone',
            field=models.CharField(choices=[('PS', 'Pink Sapphire'), ('BS', 'Blue Sapphire'), ('BD', 'Brilliant Diamond')], max_length=2),
        ),
    ]
