# Generated by Django 5.2 on 2025-04-06 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_bracelet_gemstone_alter_dropearring_gemstone_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gemstone',
        ),
    ]
