# Generated by Django 5.2 on 2025-04-15 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_color_alter_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='stone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.stone'),
            preserve_default=False,
        ),
    ]
