# Generated by Django 5.2 on 2025-04-15 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_stone_product_stone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Color',
            new_name='Gemstone',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stone',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='color',
            new_name='gemstone',
        ),
        migrations.DeleteModel(
            name='Stone',
        ),
    ]
