# Generated by Django 5.2 on 2025-04-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_gemstone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gemstone', models.CharField(choices=[('PS', 'Pink Sapphire'), ('BS', 'Blue Sapphire'), ('BD', 'Brilliant Diamond')], max_length=2)),
                ('first_image_url', models.URLField()),
                ('second_image_url', models.URLField()),
                ('description', models.TextField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('size', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
