# Generated by Django 5.2 on 2025-04-05 14:16

import django.core.validators
import django.db.models.deletion
import djangoTSGems.accounts.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', djangoTSGems.accounts.managers.AppUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AppAddress',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(validators=[django.core.validators.RegexValidator(message='Please enter a valid 16 digit card number', regex='^\\+?\\d{9,15}$')])),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=255)),
                ('apartment', models.CharField(blank=True, max_length=20, null=True)),
                ('postal_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AppPayment',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('card_holder', models.CharField(max_length=100)),
                ('card_number', models.CharField(validators=[django.core.validators.RegexValidator(message='Please enter a valid 16 digit card number', regex='^\\d{16}$')])),
                ('expiry_date', models.CharField(validators=[django.core.validators.RegexValidator(message='Please enter a valid expiry date', regex='^(0[1-9]|1[0-2])\\/\\d{2}$')])),
                ('cvv_code', models.CharField(validators=[django.core.validators.RegexValidator(message='Please enter your card’s 3-digit security code', regex='^\\d{3}$')])),
            ],
        ),
    ]
