# Generated by Django 5.2 on 2025-05-02 10:53

import django.core.validators
import django.db.models.deletion
import django_ts_gems.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.city'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.state'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='street_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.streetaddress'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='zip_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.zipcode'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=30, null=True, validators=[django_ts_gems.accounts.validators.NameValidator()]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=30, null=True, validators=[django_ts_gems.accounts.validators.NameValidator()]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(9), django_ts_gems.accounts.validators.OnlyDigitsValidator()]),
        ),
    ]
