# Generated by Django 5.2 on 2025-04-17 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='State',
        ),
        migrations.RenameModel(
            old_name='PostalCode',
            new_name='ZipCode',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='country',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='streetaddress',
            old_name='postal_code',
            new_name='zip_code',
        ),
    ]
