web: gunicorn src.wsgi:application --workers 3 --bind 0.0.0.0:$PORT
worker: celery -A src worker --loglevel=info
beat: celery -A src beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler