# Models
LLM_MODEL = 'gpt-4.1'
EMBEDDING_MODEL = 'text-embedding-3-small'

# Generation Parameters
MAX_TOKENS = 250
TEMPERATURE = 0
TOP_P = 0.1
FREQUENCY_PENALTY = 1.0
PRESENCE_PENALTY = 1.0

# Chunking Parameters
DIMENSIONS = 512
CHUNK_SIZE = 550
CHUNK_OVERLAP = 0
TOP_N_RESULTS = 5
