# Generated by Django 5.2.1 on 2025-05-27 16:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphoto',
            name='photo',
            field=cloudinary.models.CloudinaryField(default='image/upload/v1748361714/silver-membership-icon-default-avatar-profile-icon-membership-icon-social-media-user-image-illustration-vector_mky68d.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
