# Generated by Django 5.2 on 2025-05-03 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Wristwear', 'Wristwear'), ('Earwear', 'Earwear'), ('Neckwear', 'Neckwear'), ('Fingerwear', 'Fingerwear')], error_messages={'unique': 'This category already exists.'}, max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Daisy', 'Daisy'), ('Gerbera', 'Gerbera'), ('Forget Me Not', 'Forget Me Not'), ('Lily', 'Lily'), ('Lotus', 'Lotus'), ('Leaf', 'Leaf'), ('Berry', 'Berry'), ('Sunflower', 'Sunflower'), ('Lily of the Valley', 'Lily of the Valley'), ('Watch', 'Watch')], error_messages={'unique': 'This collection already exists.'}, max_length=18, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Blue', 'Blue'), ('Green', 'Green'), ('Pink', 'Pink'), ('Red', 'Red'), ('White', 'White'), ('Yellow', 'Yellow')], error_messages={'unique': 'This color already exists.'}, max_length=6, unique=True)),
                ('hex_code', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Yellow Gold', 'Yellow Gold'), ('Rose Gold', 'Rose Gold'), ('Platinum', 'Platinum')], error_messages={'unique': 'This material already exists.'}, max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Stud', 'Stud'), ('Drop', 'Drop'), ('Pendant', 'Pendant'), ('Lariat', 'Lariat'), ('Tennis', 'Tennis'), ('Chain', 'Chain'), ('Watch', 'Watch'), ('Statement', 'Statement'), ('Band', 'Band'), ('Classics', 'Classics'), ('Elegant', 'Elegant')], error_messages={'unique': 'This reference already exists.'}, max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('One Size', 'One Size')], error_messages={'unique': 'This size already exists.'}, max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Aquamarine', 'Aquamarine'), ('Diamond', 'Diamond'), ('Emerald', 'Emerald'), ('Ruby', 'Ruby'), ('Sapphire', 'Sapphire')], error_messages={'unique': 'This stone already exists.'}, max_length=10, unique=True)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_image', models.URLField()),
                ('second_image', models.URLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.collection')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.material')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.reference')),
            ],
        ),
        migrations.CreateModel(
            name='StonesColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.color')),
                ('stone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.stone')),
            ],
        ),
        migrations.CreateModel(
            name='ProductItemStonesColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productitem')),
                ('stones_colors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.stonescolors')),
            ],
            options={
                'unique_together': {('product_item', 'stones_colors')},
            },
        ),
        migrations.AddField(
            model_name='productitem',
            name='stones_colors',
            field=models.ManyToManyField(through='products.ProductItemStonesColors', to='products.stonescolors'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.PositiveIntegerField()),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productitem')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.size')),
            ],
            options={
                'unique_together': {('product_item', 'size')},
            },
        ),
    ]
