# Generated by Django 5.2.1 on 2025-05-23 15:42

import django.db.models.deletion
import src.products.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('hex_code', models.CharField(max_length=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FingerwearSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NeckwearSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('image', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WristwearSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Earwear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_image', models.URLField(error_messages={'unique': 'This image already exists.'}, unique=True)),
                ('second_image', models.URLField(error_messages={'unique': 'This image already exists.'}, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.collection')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.material')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.reference')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EarwearInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.earwear')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoneByColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(unique=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.color')),
                ('stone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.stone')),
            ],
            options={
                'unique_together': {('color', 'stone')},
            },
        ),
        migrations.CreateModel(
            name='Neckwear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_image', models.URLField(error_messages={'unique': 'This image already exists.'}, unique=True)),
                ('second_image', models.URLField(error_messages={'unique': 'This image already exists.'}, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.collection')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.material')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.reference')),
                ('stone_by_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.stonebycolor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fingerwear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_image', models.URLField(error_messages={'unique': 'This image already exists.'}, unique=True)),
                ('second_image', models.URLField(error_messages={'unique': 'This image already exists.'}, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.collection')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.material')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.reference')),
                ('stone_by_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.stonebycolor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='earwear',
            name='stone_by_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.stonebycolor'),
        ),
        migrations.CreateModel(
            name='Wristwear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_image', models.URLField(error_messages={'unique': 'This image already exists.'}, unique=True)),
                ('second_image', models.URLField(error_messages={'unique': 'This image already exists.'}, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.collection')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.material')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.reference')),
                ('stone_by_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.stonebycolor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FingerwearInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.fingerwear')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.fingerwearsize')),
            ],
            options={
                'unique_together': {('product', 'size')},
            },
            bases=(src.products.mixins.InventoryInfoMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NeckwearInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.neckwear')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.neckwearsize')),
            ],
            options={
                'unique_together': {('product', 'size')},
            },
            bases=(src.products.mixins.InventoryInfoMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WristwearInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.wristwear')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.wristwearsize')),
            ],
            options={
                'unique_together': {('product', 'size')},
            },
            bases=(src.products.mixins.InventoryInfoMixin, models.Model),
        ),
    ]
