# Generated by Django 5.2 on 2025-05-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
