# Generated by Django 5.2.1 on 2025-07-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(help_text='Review comment is required.'),
        ),
    ]
