# Generated by Django 5.2.1 on 2025-05-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2020-10-09'),
            preserve_default=False,
        ),
    ]
