# Generated by Django 5.2.1 on 2025-05-17 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('category', 'collection', 'reference', 'first_image', 'size')},
        ),
    ]
