# Generated by Django 5.2.1 on 2025-07-18 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(300)]),
        ),
    ]
