# Generated by Django 5.2.1 on 2025-06-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'permissions': [('approve_review', 'Can approve reviews')]},
        ),
        migrations.AddField(
            model_name='review',
            name='approved',
            field=models.BooleanField(default=False, help_text='Indicates whether the review has been approved by an admin.'),
        ),
    ]
