# Generated by Django 5.2.1 on 2025-05-28 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fingerwearsize',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='neckwearsize',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='wristwearsize',
            options={'ordering': ['id']},
        ),
    ]
