# Generated by Django 5.2.1 on 2025-07-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_review_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earwear',
            name='first_image',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='earwear',
            name='second_image',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='fingerwear',
            name='first_image',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='fingerwear',
            name='second_image',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='neckwear',
            name='first_image',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='neckwear',
            name='second_image',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='wristwear',
            name='first_image',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='wristwear',
            name='second_image',
            field=models.URLField(unique=True),
        ),
    ]
