# Generated by Django 5.2 on 2025-05-03 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productvariant_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stonescolors',
            options={'verbose_name_plural': 'Gemstones'},
        ),
    ]
