# Generated by Django 5.2.1 on 2025-07-13 16:48

import src.products.validators.comment
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_earwear_first_image_alter_earwear_second_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(max_length=300, validators=[src.products.validators.comment.validate_comment_length]),
        ),
    ]
