stones = {
    'AQ': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745748232/aquamarine_b4dtyx.webp',
    'DI': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745748236/diamond_dkg8rb.webp',
    'EM': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745748237/emerald_auiwk4.webp',
    'RU': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745748233/ruby_g7idgx.webp',
    'SA': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745748233/blue-sapphire_bjwmoo.webp',
}

primary_stones = {
    'AQ': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745748232/aquamarine_b4dtyx.webp',
    'WD': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745748236/diamond_dkg8rb.webp',
    'YD': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745853383/brown-diamond-CD_xvzlf6.webp',
    'EM': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745748237/emerald_auiwk4.webp',
    'RU': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745748233/ruby_g7idgx.webp',
    'BS': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745748233/blue-sapphire_bjwmoo.webp',
    'PS': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745748232/pink-sapphire_se5pnk.webp',
    'YS': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745853383/yellow-sapphire_tukm7x.webp',
}

colors = {
    'BL': '#719cf0',
    'GR': '#06986f',
    'PI': '#fa94ac',
    'RE': '#e93e3e',
    'WH': '#fff',
    'YE': '#faf098',
}

products_data = [
    # CLASSICS
    # rings
    {
        'category': 'RI',
        'collection': 'CL',
        'colors': ['RE'],
        'description': 'Ruby set in platinum and 18k yellow gold, a true testament to the beauty of a lifelong promise.',
        'materials': ['PL', 'YE'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856709/5_hubupd.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856709/6_u6skcm.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856708/7_qev0xj.avif',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856709/8_ljr0yp.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856709/herolarged_l3_bri25_1h_p1skad.avif',
        'primary_stone': 'RU',
        'reference': 'STA',
        'stones': ['RU'],
        'price': 12500,
    },
    {
        'category': 'RI',
        'collection': 'CL',
        'colors': ['BL'],
        'description': 'With all the pulsating force of deep blue waters comes the Classic Winston sapphire ring set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856712/9_rirzhm.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856711/10_ehsaci.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856731/11_wiwm9v.avif',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856712/12_nc2u10.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856709/herolarged_l3_bri25_1h_p1skad.avif',
        'primary_stone': 'BS',
        'reference': 'STA',
        'stones': ['SA'],
        'price': 11500,
    },
    {
        'category': 'RI',
        'collection': 'CL',
        'colors': ['GR'],
        'description': 'An emerald-cut emerald, set in platinum and 18K yellow gold.',
        'materials': ['PL', 'YE'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856709/17_klbvd2.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856710/18_zs4glo.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856709/19_l0z4vt.avif',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856709/20_ddjwjo.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856709/herolarged_l3_bri25_1h_p1skad.avif',
        'primary_stone': 'EM',
        'reference': 'STA',
        'stones': ['RU'],
        'price': 11500,
    },
    {
        'category': 'RI',
        'collection': 'CL',
        'colors': ['YD'],
        'description': 'A yellow diamond ring, featuring an oval-shaped yellow diamond, set in platinum and 18K yellow gold.',
        'materials': ['PL', 'YE'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856713/21_ngyfat.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856713/22_na6bd9.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856713/23_ikzyro.avif',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856712/24_x0rmfk.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856709/herolarged_l3_bri25_1h_p1skad.avif',
        'primary_stone': 'YD',
        'reference': 'STA',
        'stones': ['DI'],
        'price': 16500,
    },
    # earrings
    {
        'category': 'EA',
        'collection': 'CL',
        'colors': ['BL', 'WH'],
        'description': '2 pear-shaped sapphires, 2.46 carats and 2.54 carats, and 8 pear-shaped and round brilliant diamonds weighing a total of approximately 3.06 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856713/3_gnyea3.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856713/4_zsndel.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856714/a_z0nx2q.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856714/b_mi1ads.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856714/c_hwu1so.avif',
        'primary_stone': 'BS',
        'reference': 'DR',
        'stones': ['SA', 'DI'],
        'price': 11000,
    },
    {
        'category': 'EA',
        'collection': 'CL',
        'colors': ['RE', 'WH'],
        'description': '2 pear-shaped sapphires, 2.46 carats and 2.54 carats, and 8 pear-shaped and round brilliant diamonds weighing a total of approximately 3.06 carats, set in platinum and 18K yellow gold.',
        'materials': ['PL', 'YE'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856715/1_vobkf8.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856715/2_e3seh6.png',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856714/a_z0nx2q.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856714/b_mi1ads.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856714/c_hwu1so.avif',
        'primary_stone': 'RU',
        'reference': 'DR',
        'stones': ['RU', 'DI'],
        'price': 11500,
    },
    # DAISY DELIGHT
    # earrings
    {
        'category': 'EA',
        'collection': 'DA',
        'colors': ['BL', 'WH'],
        'description': '8 pear-shaped aquamarines weighing a total of approximately 1.21 carats and 58 round brilliant diamonds weighing a total of approximately 2.66 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856719/3_rk11jx.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856719/4_xwn5xn.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856715/a_fy2wjy.avif',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856715/b_kuvdmw.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856716/c_fxf8do.avif',
        'primary_stone': 'AQ',
        'reference': 'STU',
        'stones': ['AQ', 'DI'],
        'price': 3500,
    },
    {
        'category': 'EA',
        'collection': 'DA',
        'colors': ['PI', 'WH'],
        'description': '8 pear-shaped pink sapphires weighing a total of approximately 1.61 carats and 58 round brilliant diamonds weighing a total of approximately 2.66 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856718/5_dedzau.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856718/6_yvtk9l.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856715/a_fy2wjy.avif',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856715/b_kuvdmw.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856716/c_fxf8do.avif',
        'primary_stone': 'PS',
        'reference': 'STU',
        'stones': ['SA', 'DI'],
        'price': 3500,
    },
    {
        'category': 'EA',
        'collection': 'DA',
        'colors': ['YE', 'WH'],
        'description': '8 pear-shaped yellow sapphires weighing a total of approximately 1.66 carats and 58 round brilliant diamonds weighing a total of approximately 2.66 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856718/7_tfpses.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856718/8_sw1b2i.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856715/a_fy2wjy.avif',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856715/b_kuvdmw.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856716/c_fxf8do.avif',
        'primary_stone': 'YS',
        'reference': 'STU',
        'stones': ['SA', 'DI'],
        'price': 3500,
    },
    # necklaces
    {
        'category': 'NE',
        'collection': 'DA',
        'colors': ['BL', 'WH'],
        'description': '4 pear-shaped aquamarines weighing a total of approximately 0.60 carats and 29 round brilliant diamonds weighing a total of approximately 1.33 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856717/9_t7xv0z.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856717/10_y9vlpv.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856715/a_fy2wjy.avif',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856715/b_kuvdmw.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856716/c_fxf8do.avif',
        'primary_stone': 'AQ',
        'reference': 'PE',
        'stones': ['AQ', 'DI'],
        'price': 4500,
    },
    {
        'category': 'NE',
        'collection': 'DA',
        'colors': ['PI', 'WH'],
        'description': '4 pear-shaped pink sapphires weighing a total of approximately 0.77 carats and 29 round brilliant diamonds weighing a total of approximately 1.33 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856716/11_qtghkt.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856717/12_thdnpt.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856715/a_fy2wjy.avif',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856715/b_kuvdmw.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856716/c_fxf8do.avif',
        'primary_stone': 'PS',
        'reference': 'PE',
        'stones': ['SA', 'DI'],
        'price': 4500,
    },
    {
        'category': 'NE',
        'collection': 'DA',
        'colors': ['YE', 'WH'],
        'description': '4 pear-shaped yellow sapphires weighing a total of approximately 0.85 carats and 29 round brilliant diamonds weighing a total of approximately 1.33 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856719/13_fpc14g.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856716/14_rbfnho.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856715/a_fy2wjy.avif',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856715/b_kuvdmw.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856716/c_fxf8do.avif',
        'primary_stone': 'YS',
        'reference': 'PE',
        'stones': ['SA', 'DI'],
        'price': 4500,
    },
    # FORGET ME NOT
    # bracelets
    {
        'category': 'BR',
        'collection': 'FO',
        'colors': ['PI', 'WH'],
        'description': '45 pear-shaped and round brilliant pink sapphires weighing a total of approximately 4.36 carats and 33 pear-shaped, marquise and round brilliant diamonds weighing a total of approximately 4.24 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/1_y7npcs.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/2_ya3oww.png',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/38_l5one6.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/37_vxepl2.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/63_ottakt.avif',
        'primary_stone': 'PS',
        'reference': 'TE',
        'stones': ['SA', 'DI'],
        'price': 6500,
    },
    {
        'category': 'BR',
        'collection': 'FO',
        'colors': ['BL', 'WH'],
        'description': '45 pear-shaped and round brilliant sapphires weighing a total of approximately 4.17 carats and 33 pear-shaped, marquise and round brilliant diamonds weighing a total of approximately 4.24 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/3_fbzdlo.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/4_sopnsx.png',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/38_l5one6.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/37_vxepl2.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/63_ottakt.avif',
        'primary_stone': 'BS',
        'reference': 'TE',
        'stones': ['SA', 'DI'],
        'price': 6500,
    },
    {
        'category': 'BR',
        'collection': 'FO',
        'colors': ['WH'],
        'description': '78 pear-shaped, marquise, and round brilliant diamonds, weighing a total of approximately 7.46 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856721/5_rnjeth.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/6_f3wa3j.png',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/38_l5one6.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/37_vxepl2.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/63_ottakt.avif',
        'primary_stone': 'WD',
        'reference': 'TE',
        'stones': ['DI'],
        'price': 7000,
    },
    {
        'category': 'BR',
        'collection': 'FO',
        'colors': ['WH', 'RE'],
        'description': '45 pear-shaped and round rubies weighing a total of approximately 4.43 carats and 33 pear-shaped, marquise and round brilliant diamonds weighing a total of approximately 4.37 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/61_o98ral.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856721/62_crfies.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/38_l5one6.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/37_vxepl2.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/63_ottakt.avif',
        'primary_stone': 'RU',
        'reference': 'TE',
        'stones': ['DI', 'RU'],
        'price': 6700,
    },
    # earrings
    {
        'category': 'EA',
        'collection': 'FO',
        'colors': ['WH'],
        'description': '12 pear-shaped diamonds and 2 round brilliant diamonds weighing a total of approximately 1.70 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856729/7_vfgsqw.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856729/8_epbt6a.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/38_l5one6.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/37_vxepl2.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/63_ottakt.avif',
        'primary_stone': 'WD',
        'reference': 'STU',
        'stones': ['DI'],
        'price': 4700,
    },
    {
        'category': 'EA',
        'collection': 'FO',
        'colors': ['WH', 'PI'],
        'description': '12 pear-shaped pink sapphires weighing a total of approximately 2.20 carats and 2 round brilliant diamonds weighing a total of approximately 0.07 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856730/9_oepbcz.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856731/10_h5iil7.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/38_l5one6.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/37_vxepl2.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/63_ottakt.avif',
        'primary_stone': 'PS',
        'reference': 'STU',
        'stones': ['DI', 'SA'],
        'price': 4500,
    },
    {
        'category': 'EA',
        'collection': 'FO',
        'colors': ['WH', 'BS'],
        'description': '12 pear-shaped sapphires weighing a total of approximately 2.10 carats and 2 round brilliant diamonds weighing a total of approximately 0.07 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856730/11_pkei2s.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856730/12_wuy4n5.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/38_l5one6.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/37_vxepl2.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/63_ottakt.avif',
        'primary_stone': 'BS',
        'reference': 'STU',
        'stones': ['DI', 'SA'],
        'price': 4500,
    },
    # pendants
    {
        'category': 'NE',
        'collection': 'FO',
        'colors': ['WH'],
        'description': '6 pear-shaped and 1 round brilliant diamond weighing a total of approximately 1.07 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856725/19_qvdzj7.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856725/20_hhtxfz.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/38_l5one6.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/37_vxepl2.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/63_ottakt.avif',
        'primary_stone': 'WD',
        'reference': 'PE',
        'stones': ['DI'],
        'price': 7700,
    },
    {
        'category': 'NE',
        'collection': 'FO',
        'colors': ['WH', 'PI'],
        'description': '6 pear-shaped pink sapphires weighing a total of approximately 1.44 carats and 1 round brilliant diamond weighing approximately 0.04 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856726/21_ekvmgg.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856727/22_tzvvcv.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/38_l5one6.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/37_vxepl2.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/63_ottakt.avif',
        'primary_stone': 'PS',
        'reference': 'PE',
        'stones': ['DI', 'SA'],
        'price': 7500,
    },
    {
        'category': 'NE',
        'collection': 'FO',
        'colors': ['WH', 'BL'],
        'description': '6 pear-shaped sapphires weighing a total of approximately 1.41 carats and 1 round brilliant diamond weighing approximately 0.04 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856726/23_iwaai6.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856726/24_sqx9h1.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/38_l5one6.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/37_vxepl2.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/63_ottakt.avif',
        'primary_stone': 'BS',
        'reference': 'PE',
        'stones': ['DI', 'SA'],
        'price': 7500,
    },
    {
        'category': 'NE',
        'collection': 'FO',
        'colors': ['WH', 'RE'],
        'description': '6 pear-shaped rubies weighing a total of approximately 1.68 carats and 1 round brilliant diamond weighing a total of approximately 0.04 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856726/39_jrwngf.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856725/40_juxvhh.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/38_l5one6.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/37_vxepl2.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/63_ottakt.avif',
        'primary_stone': 'RU',
        'reference': 'PE',
        'stones': ['DI', 'RU'],
        'price': 7600,
    },
    {
        'category': 'NE',
        'collection': 'FO',
        'colors': ['WH'],
        'description': '177 pear-shaped, marquise, and round brilliant diamonds, weighing a total of approximately 15.35 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856727/25_oqbvq3.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856727/26_gnnsd4.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/38_l5one6.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/37_vxepl2.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/63_ottakt.avif',
        'primary_stone': 'WD',
        'reference': 'LA',
        'stones': ['DI'],
        'price': 9800,
    },
    {
        'category': 'NE',
        'collection': 'FO',
        'colors': ['WH', 'PI'],
        'description': '78 pear-shaped and round brilliant pink sapphires weighing a total of approximately 8.61 carats and 99 marquise and round brilliant diamonds weighing a total of approximately 8.60 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856729/27_i1bprh.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856729/28_ro5rxy.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/38_l5one6.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/37_vxepl2.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/63_ottakt.avif',
        'primary_stone': 'PS',
        'reference': 'LA',
        'stones': ['DI', 'SA'],
        'price': 9500,
    },
    {
        'category': 'NE',
        'collection': 'FO',
        'colors': ['WH', 'BL'],
        'description': '78 pear-shaped and round brilliant sapphires weighing a total of approximately 8.61 carats and 99 marquise and round brilliant diamonds weighing a total of approximately 8.37 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856728/29_efdhpn.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856728/30_zmf8x5.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/38_l5one6.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/37_vxepl2.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/63_ottakt.avif',
        'primary_stone': 'BS',
        'reference': 'LA',
        'stones': ['DI', 'SA'],
        'price': 9500,
    },
    {
        'category': 'NE',
        'collection': 'FO',
        'colors': ['WH', 'RE'],
        'description': '78 pear-shaped and round rubies weighing a total of approximately 9.13 carats and 99 marquise and round brilliant diamonds weighing a total of approximately 8.51 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856728/50_cox6xw.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856727/60_n2uukj.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/38_l5one6.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/37_vxepl2.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/63_ottakt.avif',
        'primary_stone': 'RU',
        'reference': 'LA',
        'stones': ['DI', 'RU'],
        'price': 9600,
    },
    # rings
    {
        'category': 'RI',
        'collection': 'FO',
        'colors': ['WH', 'BL'],
        'description': '6 pear-shaped sapphires weighing a total of approximately 2.15 carats and 1 round brilliant diamond weighing approximately 0.05 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/31_mh5xwc.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/32_o1zcqo.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/38_l5one6.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/37_vxepl2.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/63_ottakt.avif',
        'primary_stone': 'BS',
        'reference': 'LA',
        'stones': ['DI', 'SA'],
        'price': 4000,
    },
    {
        'category': 'RI',
        'collection': 'FO',
        'colors': ['WH'],
        'description': '6 pear-shaped and 1 round brilliant diamond, weighing a total of approximately 1.66 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856724/33_zrcek3.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856724/34_jbcbau.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/38_l5one6.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/37_vxepl2.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/63_ottakt.avif',
        'primary_stone': 'WD',
        'reference': 'STA',
        'stones': ['DI'],
        'price': 4200,
    },
    {
        'category': 'RI',
        'collection': 'FO',
        'colors': ['WH', 'PI'],
        'description': '6 pear-shaped pink sapphires weighing a total of approximately 2.22 carats and 1 round brilliant diamond weighing approximately 0.05 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/35_xcx85g.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856724/36_hlqb5d.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/38_l5one6.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/37_vxepl2.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/63_ottakt.avif',
        'primary_stone': 'PS',
        'reference': 'STA',
        'stones': ['DI', 'SA'],
        'price': 4200,
    },
    # GERBERA DAISY
    # bracelets
    {
        'category': 'BR',
        'collection': 'GE',
        'colors': ['WI'],
        'description': '29 round brilliant diamonds weighing a total of approximately 0.29 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856733/7_yopjx2.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856734/8_nnmrem.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/sbs_pdp_winstongates_eoosbz.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856733/373107_abdcs8.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/herolarged_pdp_winstongates_sxltqh.jpg',
        'primary_stone': 'WD',
        'reference': 'CH',
        'stones': ['DI'],
        'price': 3700,
    },
    {
        'category': 'BR',
        'collection': 'GE',
        'colors': ['WI'],
        'description': '29 round brilliant diamonds weighing a total of approximately 0.29 carats, set in 18K yellow gold.',
        'materials': ['YE'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/9_meqctb.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/10_wufmzy.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/sbs_pdp_winstongates_eoosbz.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856733/373107_abdcs8.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/herolarged_pdp_winstongates_sxltqh.jpg',
        'primary_stone': 'WD',
        'reference': 'CH',
        'stones': ['DI'],
        'price': 3500,
    },
    {
        'category': 'BR',
        'collection': 'GE',
        'colors': ['WI'],
        'description': '29 round brilliant diamonds weighing a total of approximately 0.29 carats, set in 18K rose gold.',
        'materials': ['RO'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856734/11_vkbeky.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856734/12_tjzjkt.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/sbs_pdp_winstongates_eoosbz.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856733/373107_abdcs8.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/herolarged_pdp_winstongates_sxltqh.jpg',
        'primary_stone': 'WD',
        'reference': 'CH',
        'stones': ['DI'],
        'price': 3500,
    },
    # earrings
    {
        'category': 'EA',
        'collection': 'GE',
        'colors': ['WI'],
        'description': '58 round brilliant diamonds weighing a total of approximately 0.43 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856739/19_vjeigd.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856739/20_vc8sus.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/sbs_pdp_winstongates_eoosbz.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856733/373107_abdcs8.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/herolarged_pdp_winstongates_sxltqh.jpg',
        'primary_stone': 'WD',
        'reference': 'STU',
        'stones': ['DI'],
        'price': 3100,
    },
    {
        'category': 'EA',
        'collection': 'GE',
        'colors': ['WI'],
        'description': '58 round brilliant diamonds weighing a total of approximately 0.43 carats, set in 18K yellow gold.',
        'materials': ['YE'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856741/21_uxbxeb.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856740/22_sd9e4h.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/sbs_pdp_winstongates_eoosbz.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856733/373107_abdcs8.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/herolarged_pdp_winstongates_sxltqh.jpg',
        'primary_stone': 'WD',
        'reference': 'STU',
        'stones': ['DI'],
        'price': 3000,
    },
    {
        'category': 'EA',
        'collection': 'GE',
        'colors': ['WI'],
        'description': '58 round brilliant diamonds weighing a total of approximately 0.43 carats, set in 18K rose gold.',
        'materials': ['RS'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856740/23_quvkpx.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856740/24_viti3i.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/sbs_pdp_winstongates_eoosbz.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856733/373107_abdcs8.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/herolarged_pdp_winstongates_sxltqh.jpg',
        'primary_stone': 'WD',
        'reference': 'STU',
        'stones': ['DI'],
        'price': 3000,
    },
    # necklaces
    {
        'category': 'NE',
        'collection': 'GE',
        'colors': ['WI'],
        'description': '29 round brilliant diamonds weighing a total of approximately 0.29 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856738/1_szzi1c.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856737/2_hzextj.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/sbs_pdp_winstongates_eoosbz.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856733/373107_abdcs8.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/herolarged_pdp_winstongates_sxltqh.jpg',
        'primary_stone': 'WD',
        'reference': 'PE',
        'stones': ['DI'],
        'price': 4200,
    },
    {
        'category': 'NE',
        'collection': 'GE',
        'colors': ['WI'],
        'description': '29 round brilliant diamonds weighing a total of approximately 0.29 carats, set in 18K yellow gold.',
        'materials': ['YE'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856739/3_wupysj.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856739/4_k9a4uv.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/sbs_pdp_winstongates_eoosbz.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856733/373107_abdcs8.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/herolarged_pdp_winstongates_sxltqh.jpg',
        'primary_stone': 'WD',
        'reference': 'PE',
        'stones': ['DI'],
        'price': 4000,
    },
    {
        'category': 'NE',
        'collection': 'GE',
        'colors': ['WI'],
        'description': '29 round brilliant diamonds weighing a total of approximately 0.29 carats, set in 18K rose gold.',
        'materials': ['RO'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856738/5_rrlmoe.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856738/6_iackza.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/sbs_pdp_winstongates_eoosbz.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856733/373107_abdcs8.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/herolarged_pdp_winstongates_sxltqh.jpg',
        'primary_stone': 'WD',
        'reference': 'PE',
        'stones': ['DI'],
        'price': 4000,
    },
    # rings
    {
        'category': 'RI',
        'collection': 'GE',
        'colors': ['WI'],
        'description': '31 round brilliant diamonds weighing a total of approximately 0.40 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856737/13_xgwtpr.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856736/14_kqxkvo.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/sbs_pdp_winstongates_eoosbz.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856733/373107_abdcs8.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/herolarged_pdp_winstongates_sxltqh.jpg',
        'primary_stone': 'WD',
        'reference': 'STA',
        'stones': ['DI'],
        'price': 3600,
    },
    {
        'category': 'RI',
        'collection': 'GE',
        'colors': ['WI'],
        'description': '31 round brilliant diamonds weighing a total of approximately 0.40 carats, set in 18K yellow gold.',
        'materials': ['YE'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856736/15_rekqju.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856736/15_rekqju.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/sbs_pdp_winstongates_eoosbz.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856733/373107_abdcs8.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/herolarged_pdp_winstongates_sxltqh.jpg',
        'primary_stone': 'WD',
        'reference': 'STA',
        'stones': ['DI'],
        'price': 3400,
    },
    {
        'category': 'RI',
        'collection': 'GE',
        'colors': ['WI'],
        'description': '31 round brilliant diamonds weighing a total of approximately 0.40 carats, set in 18K rose gold.',
        'materials': ['YE'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856736/17_t26gka.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856736/18_jqpfrr.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/sbs_pdp_winstongates_eoosbz.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856733/373107_abdcs8.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/herolarged_pdp_winstongates_sxltqh.jpg',
        'primary_stone': 'WD',
        'reference': 'STA',
        'stones': ['DI'],
        'price': 3400,
    },
    # LILY BLOOM
    # bracelets
    {
        'category': 'BR',
        'collection': 'LI',
        'colors': ['WH'],
        'description': '75 round brilliant diamonds set in warm 18k yellow gold, this timeless piece captures one of nature’s most beautiful blooms.',
        'materials': ['YE'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856742/1_anxylk.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/2_z9ntu6.png',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856741/lily24_pdp_b_3_akkd7v.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/lily24_pdp_c_e1ihow.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/28_mqzog7.avif',
        'primary_stone': 'WD',
        'reference': 'CH',
        'stones': ['DI'],
        'price': 3000,
    },
    {
        'category': 'BR',
        'collection': 'LI',
        'colors': ['WH'],
        'description': '75 round brilliant diamonds, each masterfully set in lustrous platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856741/5_wcemq4.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856742/6_tkfzty.png',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856741/lily24_pdp_b_3_akkd7v.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/lily24_pdp_c_e1ihow.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/28_mqzog7.avif',
        'primary_stone': 'WD',
        'reference': 'CH',
        'stones': ['DI'],
        'price': 3200,
    },
    {
        'category': 'BR',
        'collection': 'LI',
        'colors': ['WH'],
        'description': '47 round brilliant diamonds weighing a total of approximately 0.31 carats, set in 18K rose gold. ',
        'materials': ['RO'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856741/3_zafs4t.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856742/4_jbijwg.png',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856741/lily24_pdp_b_3_akkd7v.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/lily24_pdp_c_e1ihow.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/28_mqzog7.avif',
        'primary_stone': 'WD',
        'reference': 'CH',
        'stones': ['DI'],
        'price': 3200,
    },
    # necklaces
    {
        'category': 'NE',
        'collection': 'LI',
        'colors': ['WH'],
        'description': '1 marquise and 45 round brilliant diamonds weighing a total of approximately 0.68 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856746/12_bdrupe.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856746/13_fe4z7n.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856741/lily24_pdp_b_3_akkd7v.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/lily24_pdp_c_e1ihow.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/28_mqzog7.avif',
        'primary_stone': 'WD',
        'reference': 'PE',
        'stones': ['DI'],
        'price': 3700,
    },
    {
        'category': 'NE',
        'collection': 'LI',
        'colors': ['WH'],
        'description': '1 marquise and 45 round brilliant diamonds weighing a total of approximately 0.68 carats, set in 18K yellow gold.',
        'materials': ['YE'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857651/14_wlqhbf.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857651/15_xbyed3.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856741/lily24_pdp_b_3_akkd7v.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/lily24_pdp_c_e1ihow.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/28_mqzog7.avif',
        'primary_stone': 'WD',
        'reference': 'PE',
        'stones': ['DI'],
        'price': 3500,
    },
    {
        'category': 'NE',
        'collection': 'LI',
        'colors': ['WH'],
        'description': '1 marquise and 45 round brilliant diamonds weighing a total of approximately 0.68 carats, set in 18K rose gold.',
        'materials': ['RO'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857651/16_m4ae1k.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856791/17_ywdinc.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856741/lily24_pdp_b_3_akkd7v.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/lily24_pdp_c_e1ihow.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/28_mqzog7.avif',
        'primary_stone': 'WD',
        'reference': 'PE',
        'stones': ['DI'],
        'price': 3500,
    },
    {
        'category': 'NE',
        'collection': 'LI',
        'colors': ['WH'],
        'description': '619 round brilliant diamonds weighing a total of approximately 5.33 carats, set in 18K yellow gold.',
        'materials': ['YE'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857652/24_lt0t4w.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857652/25_o5odgo.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856741/lily24_pdp_b_3_akkd7v.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/lily24_pdp_c_e1ihow.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/28_mqzog7.avif',
        'primary_stone': 'WD',
        'reference': 'LA',
        'stones': ['DI'],
        'price': 4500,
    },
    {
        'category': 'NE',
        'collection': 'LI',
        'colors': ['WH'],
        'description': '619 round brilliant diamonds weighing a total of approximately 5.33 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857652/26_xp6skd.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857653/27_jnubbq.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856741/lily24_pdp_b_3_akkd7v.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/lily24_pdp_c_e1ihow.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/28_mqzog7.avif',
        'primary_stone': 'WD',
        'reference': 'LA',
        'stones': ['DI'],
        'price': 4700,
    },
    # rings
    {
        'category': 'RI',
        'collection': 'LI',
        'colors': ['WH'],
        'description': '1 marquise and 54 round brilliant diamonds weighing a total of approximately 0.41 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856744/18_i6mhsa.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856744/19_rkivut.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856741/lily24_pdp_b_3_akkd7v.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/lily24_pdp_c_e1ihow.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/28_mqzog7.avif',
        'primary_stone': 'WD',
        'reference': 'STA',
        'stones': ['DI'],
        'price': 2700,
    },
    {
        'category': 'RI',
        'collection': 'LI',
        'colors': ['WH'],
        'description': '1 marquise and 54 round brilliant diamonds weighing a total of approximately 0.41 carats, set in 18k yellow gold.',
        'materials': ['YE'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856745/20_aahcgy.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856745/21_bgldka.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856741/lily24_pdp_b_3_akkd7v.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/lily24_pdp_c_e1ihow.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/28_mqzog7.avif',
        'primary_stone': 'WD',
        'reference': 'STA',
        'stones': ['DI'],
        'price': 2500,
    },
    {
        'category': 'RI',
        'collection': 'LI',
        'colors': ['WH'],
        'description': '1 marquise and 54 round brilliant diamonds weighing a total of approximately 0.41 carats, set in 18K rose gold.',
        'materials': ['RO'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856745/22_zdywno.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856747/23_f6ywtz.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856741/lily24_pdp_b_3_akkd7v.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/lily24_pdp_c_e1ihow.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/28_mqzog7.avif',
        'primary_stone': 'WD',
        'reference': 'STA',
        'stones': ['DI'],
        'price': 2500,
    },
    # RADIANT CLUSTER
    # earrings
    {
        'category': 'EA',
        'collection': 'RA',
        'colors': ['WH', 'BL'],
        'description': '2 round and 2 pear-shaped sapphires weighing a total of approximately 1.90 carats, 4 round aquamarines weighing a total of approximately 1.00 carat, and 12 round brilliant and pear-shaped diamonds weighing a total of approximately 1.79 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857655/1_dkjm1v.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857655/2_g1gutd.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857659/EdJqsYLXoAEsxjB_rzyydb.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857658/sparklingcluster_augsx5.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857656/herolarged_pdp_sparklingcluster_u6a1y9.avif',
        'primary_stone': 'BS',
        'reference': 'DR',
        'stones': ['AQ', 'DI', 'SA'],
        'price': 8000,
    },
    {
        'category': 'EA',
        'collection': 'RA',
        'colors': ['WH'],
        'description': '16 round brilliant and 4 pear-shaped diamonds weighing a total of 4.27 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857656/3_k6pqt4.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857656/4_mh5x93.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857659/EdJqsYLXoAEsxjB_rzyydb.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857658/sparklingcluster_augsx5.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857656/herolarged_pdp_sparklingcluster_u6a1y9.avif',
        'primary_stone': 'WD',
        'reference': 'DR',
        'stones': ['DI'],
        'price': 8500,
    },
    # necklaces
    {
        'category': 'NE',
        'collection': 'RA',
        'colors': ['WH', 'BL'],
        'description': '2 round sapphires weighing a total of approximately 0.98 carats, 1 round and 1 pear-shaped aquamarine weighing a total of approximately 0.23 carats, and 7 round brilliant and pear-shaped diamonds weighing a total of approximately 1.20 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857662/5_yzdqh0.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857662/6_i7fhrp.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857659/EdJqsYLXoAEsxjB_rzyydb.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857658/sparklingcluster_augsx5.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857656/herolarged_pdp_sparklingcluster_u6a1y9.avif',
        'primary_stone': 'BS',
        'reference': 'PE',
        'stones': ['DI', 'AQ', 'SA'],
        'price': 10000,
    },
    {
        'category': 'NE',
        'collection': 'RA',
        'colors': ['WH'],
        'description': '9 round brilliant and 2 pear-shaped diamonds weighing a total of approximately 2.28 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857662/7_cfqknr.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857663/8_gi7190.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857659/EdJqsYLXoAEsxjB_rzyydb.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857658/sparklingcluster_augsx5.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857656/herolarged_pdp_sparklingcluster_u6a1y9.avif',
        'primary_stone': 'WD',
        'reference': 'PE',
        'stones': ['DI'],
        'price': 10500,
    },
    {
        'category': 'NE',
        'collection': 'RA',
        'colors': ['WH', 'BL'],
        'description': '25 round and pear-shaped sapphires weighing a total of approximately 4.45 carats, 23 round aquamarines weighing a total of approximately 2.80 carats, and 130 round brilliant and pear-shaped diamonds weighing a total of approximately 8.73 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857663/9_ymv9af.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857663/10_xxv5vo.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857659/EdJqsYLXoAEsxjB_rzyydb.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857658/sparklingcluster_augsx5.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857656/herolarged_pdp_sparklingcluster_u6a1y9.avif',
        'primary_stone': 'BS',
        'reference': 'LA',
        'stones': ['DI', 'AQ', 'SA'],
        'price': 11000,
    },
    {
        'category': 'NE',
        'collection': 'RA',
        'colors': ['WH', 'BL'],
        'description': '148 round brilliant and 3 pear-shaped diamonds weighing a total of approximately 15.18 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857665/11_iydf2f.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857665/12_zlxyyo.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857659/EdJqsYLXoAEsxjB_rzyydb.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857658/sparklingcluster_augsx5.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857656/herolarged_pdp_sparklingcluster_u6a1y9.avif',
        'primary_stone': 'WD',
        'reference': 'LA',
        'stones': ['DI'],
        'price': 11500,
    },
    # rings
    {
        'category': 'RI',
        'collection': 'RA',
        'colors': ['WH', 'BL'],
        'description': '1 pear-shaped and 2 round sapphires weighing a total of approximately 1.08 carats, 2 round aquamarines weighing a total of approximately 0.38 carats, and 7 round brilliant and pear-shaped diamonds weighing a total of approximately 1.19 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857660/13_djdqv1.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857659/14_yhokna.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857659/EdJqsYLXoAEsxjB_rzyydb.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857658/sparklingcluster_augsx5.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857656/herolarged_pdp_sparklingcluster_u6a1y9.avif',
        'primary_stone': 'BS',
        'reference': 'STA',
        'stones': ['DI', 'AQ', 'SA'],
        'price': 6000,
    },
    {
        'category': 'RI',
        'collection': 'RA',
        'colors': ['WH'],
        'description': '10 round brilliant and 2 pear-shaped diamonds weighing a total of approximately 2.34 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857661/15_izdvu7.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857661/16_a9yioa.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857659/EdJqsYLXoAEsxjB_rzyydb.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857658/sparklingcluster_augsx5.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857656/herolarged_pdp_sparklingcluster_u6a1y9.avif',
        'primary_stone': 'WD',
        'reference': 'STA',
        'stones': ['DI'],
        'price': 6500,
    },
    # SPARKLING LOTUS
    # earrings
    {
        'category': 'EA',
        'collection': 'SP',
        'colors': ['GR', 'WH'],
        'description': '6 marquise and pear-shaped emeralds weighing a total of approximately 2.65 carats and 8 marquise and pear-shaped diamonds weighing a total of approximately 2.88 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857666/1_ixcye4.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857666/2_alvog0.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857670/sbs_pdp_winstoncluster_wui3gn.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857670/29_liwwgd.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857666/herolarged_pdp_winstoncluster_oanc0d.avif',
        'primary_stone': 'EM',
        'reference': 'STU',
        'stones': ['DI', 'EM'],
        'price': 5000,
    },
    {
        'category': 'EA',
        'collection': 'SP',
        'colors': ['RE', 'WH'],
        'description': '6 marquise and pear-shaped rubies weighing a total of approximately 3.50 carats and 8 marquise and pear-shaped diamonds weighing a total of approximately 2.92 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857670/3_blncz2.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857669/4_lkvum4.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857670/sbs_pdp_winstoncluster_wui3gn.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857670/29_liwwgd.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857666/herolarged_pdp_winstoncluster_oanc0d.avif',
        'primary_stone': 'RU',
        'reference': 'STU',
        'stones': ['DI', 'RU'],
        'price': 5000,
    },
    {
        'category': 'EA',
        'collection': 'SP',
        'colors': ['BL', 'WH'],
        'description': '6 marquise and pear-shaped sapphires weighing a total of approximately 3.20 carats and 8 marquise and pear-shaped diamonds weighing a total of approximately 2.88 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857669/5_lueuid.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857668/6_fkrmjj.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857670/sbs_pdp_winstoncluster_wui3gn.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857670/29_liwwgd.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857666/herolarged_pdp_winstoncluster_oanc0d.avif',
        'primary_stone': 'BS',
        'reference': 'STU',
        'stones': ['DI', 'SA'],
        'price': 5000,
    },
    {
        'category': 'EA',
        'collection': 'SP',
        'colors': ['WH'],
        'description': '6 pear-shaped and 4 marquise diamonds weighing a total of approximately 7.83 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857667/33_pvhyud.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857667/34_xqqfih.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857670/sbs_pdp_winstoncluster_wui3gn.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857670/29_liwwgd.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857666/herolarged_pdp_winstoncluster_oanc0d.avif',
        'primary_stone': 'WD',
        'reference': 'STU',
        'stones': ['DI'],
        'price': 5500,
    },
    # necklaces
    {
        'category': 'NE',
        'collection': 'SP',
        'colors': ['WH', 'RE'],
        'description': '3 marquise and pear-shaped rubies weighing a total of approximately 2.50 carats and 4 marquise and pear-shaped diamonds weighing a total of approximately 2.21 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857674/15_iekkxm.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857674/16_arjkr0.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857670/sbs_pdp_winstoncluster_wui3gn.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857670/29_liwwgd.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857666/herolarged_pdp_winstoncluster_oanc0d.avif',
        'primary_stone': 'RU',
        'reference': 'PE',
        'stones': ['DI', 'RU'],
        'price': 11000,
    },
    {
        'category': 'NE',
        'collection': 'SP',
        'colors': ['WH', 'BL'],
        'description': '3 marquise and pear-shaped sapphires weighing a total of 2.50 carats and 4 marquise and pear-shaped diamonds weighing a total of approximately 2.15 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857676/17_is4la0.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857675/18_bd01u0.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857670/sbs_pdp_winstoncluster_wui3gn.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857670/29_liwwgd.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857666/herolarged_pdp_winstoncluster_oanc0d.avif',
        'primary_stone': 'BS',
        'reference': 'PE',
        'stones': ['DI', 'SA'],
        'price': 11000,
    },
    {
        'category': 'NE',
        'collection': 'SP',
        'colors': ['WH', 'GR'],
        'description': '3 marquise and pear-shaped emeralds weighing a total of approximately 2.00 carats and 4 marquise and pear-shaped diamonds weighing a total of approximately 2.15 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857675/19_fbrqq4.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857675/20_sg2qlv.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857670/sbs_pdp_winstoncluster_wui3gn.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857670/29_liwwgd.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857666/herolarged_pdp_winstoncluster_oanc0d.avif',
        'primary_stone': 'EM',
        'reference': 'PE',
        'stones': ['DI', 'EM'],
        'price': 10500,
    },
    # rings
    {
        'category': 'RI',
        'collection': 'SP',
        'colors': ['WH', 'RE'],
        'description': '3 marquise and pear-shaped rubies weighing a total of approximately 2.41 carats and 4 marquise and pear-shaped diamonds weighing a total of approximately 2.10 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857671/27_lcupz0.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857672/28_oondpf.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857670/sbs_pdp_winstoncluster_wui3gn.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857670/29_liwwgd.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857666/herolarged_pdp_winstoncluster_oanc0d.avif',
        'primary_stone': 'RU',
        'reference': 'STA',
        'stones': ['DI', 'RU'],
        'price': 6000,
    },
    {
        'category': 'RI',
        'collection': 'SP',
        'colors': ['WH', 'BL'],
        'description': '3 marquise and pear-shaped sapphires weighing a total of approximately 2.81 carats and 4 marquise and pear-shaped diamonds weighing a total of approximately 2.10 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857673/31_x759kl.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857673/32_cyss0x.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857670/sbs_pdp_winstoncluster_wui3gn.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857670/29_liwwgd.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857666/herolarged_pdp_winstoncluster_oanc0d.avif',
        'primary_stone': 'BS',
        'reference': 'STA',
        'stones': ['DI', 'SA'],
        'price': 6000,
    },
    {
        'category': 'RI',
        'collection': 'SP',
        'colors': ['WH'],
        'description': '3 pear-shaped and 2 marquise diamonds weighing a total of approximately 3.92 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857672/37_r8qfed.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857673/38_dlldba.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857670/sbs_pdp_winstoncluster_wui3gn.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857670/29_liwwgd.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857666/herolarged_pdp_winstoncluster_oanc0d.avif',
        'primary_stone': 'WD',
        'reference': 'STA',
        'stones': ['DI'],
        'price': 6500,
    },
    # SUNFLOWER
    # earrings
    {
        'category': 'EA',
        'collection': 'SU',
        'colors': ['WH'],
        'description': '18 round brilliant diamonds weighing a total of approximately 1.60 carats, center stones are approximately 0.30 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857678/1_c2cxml.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857677/2_rluqrp.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857680/sbs_sunflower24_pdp_eelze0.webp',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857676/sbs_sunflower24_pdp_b_uwfl6j.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857682/sf_la_pdp_b_1_tuxllg.jpg',
        'primary_stone': 'WD',
        'reference': 'STU',
        'stones': ['DI'],
        'price': 3500,
    },
    {
        'category': 'EA',
        'collection': 'SU',
        'colors': ['WH', 'BL'],
        'description': '16 round brilliant diamonds weighing a total of approximately 0.90 carats with round sapphire center stones of approximately 0.44 carats each, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857679/3_lg4eht.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857679/4_w0jhlu.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857680/sbs_sunflower24_pdp_eelze0.webp',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857676/sbs_sunflower24_pdp_b_uwfl6j.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857682/sf_la_pdp_b_1_tuxllg.jpg',
        'primary_stone': 'BS',
        'reference': 'STU',
        'stones': ['DI', 'SA'],
        'price': 3000,
    },
    {
        'category': 'EA',
        'collection': 'SU',
        'colors': ['WH', 'RE'],
        'description': '16 round brilliant diamonds weighing a total of approximately 0.90 carats with round ruby center stones of approximately 0.44 carats each, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857678/5_htyctv.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857679/6_tc13fl.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857680/sbs_sunflower24_pdp_eelze0.webp',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857676/sbs_sunflower24_pdp_b_uwfl6j.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857682/sf_la_pdp_b_1_tuxllg.jpg',
        'primary_stone': 'RU',
        'reference': 'STU',
        'stones': ['DI', 'RU'],
        'price': 3000,
    },
    # necklaces
    {
        'category': 'NE',
        'collection': 'SU',
        'colors': ['WH'],
        'description': '9 round brilliant diamonds weighing a total of approximately 0.80 carats, center stone is approximately 0.30 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857682/7_hmfxs8.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857682/8_osq5sv.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857680/sbs_sunflower24_pdp_eelze0.webp',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857676/sbs_sunflower24_pdp_b_uwfl6j.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857682/sf_la_pdp_b_1_tuxllg.jpg',
        'primary_stone': 'WD',
        'reference': 'PE',
        'stones': ['DI'],
        'price': 5500,
    },
    {
        'category': 'NE',
        'collection': 'SU',
        'colors': ['WH', 'BL'],
        'description': '8 round brilliant diamonds weighing a total of approximately 0.44 carats with a round sapphire center stone of approximately 0.42 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857684/9_k4zm2j.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857684/10_o8wuha.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857680/sbs_sunflower24_pdp_eelze0.webp',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857676/sbs_sunflower24_pdp_b_uwfl6j.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857682/sf_la_pdp_b_1_tuxllg.jpg',
        'primary_stone': 'BS',
        'reference': 'PE',
        'stones': ['DI', 'SA'],
        'price': 5000,
    },
    {
        'category': 'NE',
        'collection': 'SU',
        'colors': ['WH', 'RE'],
        'description': '8 round brilliant diamonds weighing a total of approximately 0.44 carats with a round ruby center stone of approximately 0.46 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857683/11_oxpmt9.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857683/12_z36b3x.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857680/sbs_sunflower24_pdp_eelze0.webp',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857676/sbs_sunflower24_pdp_b_uwfl6j.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857682/sf_la_pdp_b_1_tuxllg.jpg',
        'primary_stone': 'RU',
        'reference': 'PE',
        'stones': ['DI', 'RU'],
        'price': 5000,
    },
    # rings
    {
        'category': 'RI',
        'collection': 'SU',
        'colors': ['WH'],
        'description': '17 round brilliant diamonds weighing a total of approximately 1.72 carats, center stone is approximately 0.70 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857680/13_w9vzy8.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857680/14_ttjlx4.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857680/sbs_sunflower24_pdp_eelze0.webp',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857676/sbs_sunflower24_pdp_b_uwfl6j.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857682/sf_la_pdp_b_1_tuxllg.jpg',
        'primary_stone': 'WD',
        'reference': 'STA',
        'stones': ['DI'],
        'price': 4000,
    },
    {
        'category': 'RI',
        'collection': 'SU',
        'colors': ['WH', 'BS'],
        'description': '18 round brilliant diamonds, weighing a total of approximately 0.58 carats with a round sapphire center stone of approximately 0.44 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857681/15_b6tjbq.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857681/16_tv68em.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857680/sbs_sunflower24_pdp_eelze0.webp',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857676/sbs_sunflower24_pdp_b_uwfl6j.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857682/sf_la_pdp_b_1_tuxllg.jpg',
        'primary_stone': 'BS',
        'reference': 'STA',
        'stones': ['DI', 'SA'],
        'price': 4000,
    },
    {
        'category': 'RI',
        'collection': 'SU',
        'colors': ['WH', 'RE'],
        'description': '18 round brilliant diamonds, weighing a total of approximately 0.58 carats with a round ruby center stone of approximately 0.44 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857680/17_acvydz.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857681/18_bkomzs.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857680/sbs_sunflower24_pdp_eelze0.webp',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857676/sbs_sunflower24_pdp_b_uwfl6j.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857682/sf_la_pdp_b_1_tuxllg.jpg',
        'primary_stone': 'RU',
        'reference': 'STA',
        'stones': ['DI', 'RU'],
        'price': 4000,
    },
]
