stones = {
    'AQ': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745748232/aquamarine_b4dtyx.webp',
    'DI': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745748236/diamond_dkg8rb.webp',
    'EM': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745748237/emerald_auiwk4.webp',
    'RU': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745748233/ruby_g7idgx.webp',
    'SA': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745748233/blue-sapphire_bjwmoo.webp',
}

primary_stones = {
    'AQ': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745748232/aquamarine_b4dtyx.webp',
    'WD': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745748236/diamond_dkg8rb.webp',
    'YD': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745853383/brown-diamond-CD_xvzlf6.webp',
    'EM': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745748237/emerald_auiwk4.webp',
    'RU': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745748233/ruby_g7idgx.webp',
    'BS': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745748233/blue-sapphire_bjwmoo.webp',
    'PS': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745748232/pink-sapphire_se5pnk.webp',
    'YS': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745853383/yellow-sapphire_tukm7x.webp',
}

colors = {
    'BU': '#719cf0',
    'GR': '#06986f',
    'PI': '#fa94ac',
    'RE': '#e93e3e',
    'WH': '#fff',
    'YE': '#faf098',
}

{
    'category': '',
    'collection': '',
    'colors': [],
    'description': '',
    'materials': [],
    'first_image': '',
    'second_image': '',
    'third_image': '',
    'fourth_image': '',
    'fifth_image': '',
    'primary_stone': '',
    'reference': '',
    'stones': [],
    'price': 0,
},


products_data = [
    # CLASSICS
    # rings
    {
        'category': 'RI',
        'collection': 'CL',
        'colors': ['RE'],
        'description': 'Ruby set in platinum and 18k yellow gold, a true testament to the beauty of a lifelong promise.',
        'materials': ['PL', 'YE'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856709/5_hubupd.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856709/6_u6skcm.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856708/7_qev0xj.avif',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856709/8_ljr0yp.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856709/herolarged_l3_bri25_1h_p1skad.avif',
        'primary_stone': 'RU',
        'reference': 'STA',
        'stones': ['RU'],
        'price': 12500,
    },
    {
        'category': 'RI',
        'collection': 'CL',
        'colors': ['BL'],
        'description': 'With all the pulsating force of deep blue waters comes the Classic Winston sapphire ring set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856712/9_rirzhm.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856711/10_ehsaci.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856731/11_wiwm9v.avif',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856712/12_nc2u10.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856709/herolarged_l3_bri25_1h_p1skad.avif',
        'primary_stone': 'BS',
        'reference': 'STA',
        'stones': ['SA'],
        'price': 11500,
    },
    {
        'category': 'RI',
        'collection': 'CL',
        'colors': ['GR'],
        'description': 'An emerald-cut emerald, set in platinum and 18K yellow gold.',
        'materials': ['PL', 'YE'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856709/17_klbvd2.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856710/18_zs4glo.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856709/19_l0z4vt.avif',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856709/20_ddjwjo.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856709/herolarged_l3_bri25_1h_p1skad.avif',
        'primary_stone': 'RU',
        'reference': 'STA',
        'stones': ['RU'],
        'price': 11500,
    },
    {
        'category': 'RI',
        'collection': 'CL',
        'colors': ['YD'],
        'description': 'A yellow diamond ring, featuring an oval-shaped yellow diamond, set in platinum and 18K yellow gold.',
        'materials': ['PL', 'YE'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856713/21_ngyfat.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856713/22_na6bd9.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856713/23_ikzyro.avif',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856712/24_x0rmfk.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856709/herolarged_l3_bri25_1h_p1skad.avif',
        'primary_stone': 'YD',
        'reference': 'STA',
        'stones': ['DI'],
        'price': 16500,
    },
    # earrings
    {
        'category': 'EA',
        'collection': 'CL',
        'colors': ['BL', 'WH'],
        'description': '2 pear-shaped sapphires, 2.46 carats and 2.54 carats, and 8 pear-shaped and round brilliant diamonds weighing a total of approximately 3.06 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856713/3_gnyea3.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856713/4_zsndel.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856714/a_z0nx2q.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856714/b_mi1ads.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856714/c_hwu1so.avif',
        'primary_stone': 'BS',
        'reference': 'DR',
        'stones': ['SA', 'DI'],
        'price': 11000,
    },
    {
        'category': 'EA',
        'collection': 'CL',
        'colors': ['RE', 'WH'],
        'description': '2 pear-shaped sapphires, 2.46 carats and 2.54 carats, and 8 pear-shaped and round brilliant diamonds weighing a total of approximately 3.06 carats, set in platinum and 18K yellow gold.',
        'materials': ['PL', 'YE'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856715/1_vobkf8.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856715/2_e3seh6.png',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856714/a_z0nx2q.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856714/b_mi1ads.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856714/c_hwu1so.avif',
        'primary_stone': 'RU',
        'reference': 'DR',
        'stones': ['RU', 'DI'],
        'price': 11500,
    },
    # DAISY DELIGHT
    # earrings
    {
        'category': 'EA',
        'collection': 'DA',
        'colors': ['BL', 'WH'],
        'description': '8 pear-shaped aquamarines weighing a total of approximately 1.21 carats and 58 round brilliant diamonds weighing a total of approximately 2.66 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856719/3_rk11jx.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856719/4_xwn5xn.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856715/a_fy2wjy.avif',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856715/b_kuvdmw.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856716/c_fxf8do.avif',
        'primary_stone': 'BS',
        'reference': 'STU',
        'stones': ['SA', 'DI'],
        'price': 3500,
    },
    {
        'category': 'EA',
        'collection': 'DA',
        'colors': ['PI', 'WH'],
        'description': '8 pear-shaped pink sapphires weighing a total of approximately 1.61 carats and 58 round brilliant diamonds weighing a total of approximately 2.66 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856718/5_dedzau.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856718/6_yvtk9l.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856715/a_fy2wjy.avif',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856715/b_kuvdmw.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856716/c_fxf8do.avif',
        'primary_stone': 'PS',
        'reference': 'STU',
        'stones': ['SA', 'DI'],
        'price': 3500,
    },
    {
        'category': 'EA',
        'collection': 'DA',
        'colors': ['YE', 'WH'],
        'description': '8 pear-shaped yellow sapphires weighing a total of approximately 1.66 carats and 58 round brilliant diamonds weighing a total of approximately 2.66 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856718/7_tfpses.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856718/8_sw1b2i.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856715/a_fy2wjy.avif',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856715/b_kuvdmw.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856716/c_fxf8do.avif',
        'primary_stone': 'YS',
        'reference': 'STU',
        'stones': ['SA', 'DI'],
        'price': 3500,
    },
    # necklaces
    {
        'category': 'NE',
        'collection': 'DA',
        'colors': ['BL', 'WH'],
        'description': '4 pear-shaped aquamarines weighing a total of approximately 0.60 carats and 29 round brilliant diamonds weighing a total of approximately 1.33 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856717/9_t7xv0z.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856717/10_y9vlpv.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856715/a_fy2wjy.avif',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856715/b_kuvdmw.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856716/c_fxf8do.avif',
        'primary_stone': 'BS',
        'reference': 'PE',
        'stones': ['SA', 'DI'],
        'price': 4500,
    },
    {
        'category': 'NE',
        'collection': 'DA',
        'colors': ['PI', 'WH'],
        'description': '4 pear-shaped pink sapphires weighing a total of approximately 0.77 carats and 29 round brilliant diamonds weighing a total of approximately 1.33 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856716/11_qtghkt.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856717/12_thdnpt.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856715/a_fy2wjy.avif',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856715/b_kuvdmw.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856716/c_fxf8do.avif',
        'primary_stone': 'PS',
        'reference': 'PE',
        'stones': ['SA', 'DI'],
        'price': 4500,
    },
    {
        'category': 'NE',
        'collection': 'DA',
        'colors': ['YE', 'WH'],
        'description': '4 pear-shaped yellow sapphires weighing a total of approximately 0.85 carats and 29 round brilliant diamonds weighing a total of approximately 1.33 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856719/13_fpc14g.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856716/14_rbfnho.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856715/a_fy2wjy.avif',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856715/b_kuvdmw.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856716/c_fxf8do.avif',
        'primary_stone': 'YS',
        'reference': 'PE',
        'stones': ['SA', 'DI'],
        'price': 4500,
    },
    # FORGET ME NOT
    # bracelets
    {
        'category': 'BR',
        'collection': 'FO',
        'colors': ['PI', 'WH'],
        'description': '45 pear-shaped and round brilliant pink sapphires weighing a total of approximately 4.36 carats and 33 pear-shaped, marquise and round brilliant diamonds weighing a total of approximately 4.24 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/1_y7npcs.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/2_ya3oww.png',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/38_l5one6.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/37_vxepl2.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/63_ottakt.avif',
        'primary_stone': 'PS',
        'reference': 'TE',
        'stones': ['SA', 'DI'],
        'price': 6500,
    },
    {
        'category': 'BR',
        'collection': 'FO',
        'colors': ['BL', 'WH'],
        'description': '45 pear-shaped and round brilliant sapphires weighing a total of approximately 4.17 carats and 33 pear-shaped, marquise and round brilliant diamonds weighing a total of approximately 4.24 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/3_fbzdlo.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/4_sopnsx.png',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/38_l5one6.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/37_vxepl2.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/63_ottakt.avif',
        'primary_stone': 'BS',
        'reference': 'TE',
        'stones': ['SA', 'DI'],
        'price': 6500,
    },
    {
        'category': 'BR',
        'collection': 'FO',
        'colors': ['WH'],
        'description': '78 pear-shaped, marquise, and round brilliant diamonds, weighing a total of approximately 7.46 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856721/5_rnjeth.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/6_f3wa3j.png',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/38_l5one6.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/37_vxepl2.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/63_ottakt.avif',
        'primary_stone': 'WD',
        'reference': 'TE',
        'stones': ['DI'],
        'price': 7000,
    },
    {
        'category': 'BR',
        'collection': 'FO',
        'colors': ['WH', 'RE'],
        'description': '45 pear-shaped and round rubies weighing a total of approximately 4.43 carats and 33 pear-shaped, marquise and round brilliant diamonds weighing a total of approximately 4.37 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/61_o98ral.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856721/62_crfies.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/38_l5one6.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/37_vxepl2.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/63_ottakt.avif',
        'primary_stone': 'RU',
        'reference': 'TE',
        'stones': ['DI', 'RU'],
        'price': 6700,
    },
    # earrings
    {
        'category': 'EA',
        'collection': 'FO',
        'colors': ['WH'],
        'description': '12 pear-shaped diamonds and 2 round brilliant diamonds weighing a total of approximately 1.70 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856729/7_vfgsqw.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856729/8_epbt6a.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/38_l5one6.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/37_vxepl2.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/63_ottakt.avif',
        'primary_stone': 'WD',
        'reference': 'STU',
        'stones': ['DI'],
        'price': 4700,
    },
    {
        'category': 'EA',
        'collection': 'FO',
        'colors': ['WH', 'PI'],
        'description': '12 pear-shaped pink sapphires weighing a total of approximately 2.20 carats and 2 round brilliant diamonds weighing a total of approximately 0.07 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856730/9_oepbcz.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856731/10_h5iil7.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/38_l5one6.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/37_vxepl2.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/63_ottakt.avif',
        'primary_stone': 'PS',
        'reference': 'STU',
        'stones': ['DI', 'SA'],
        'price': 4500,
    },
    {
        'category': 'EA',
        'collection': 'FO',
        'colors': ['WH', 'BS'],
        'description': '12 pear-shaped sapphires weighing a total of approximately 2.10 carats and 2 round brilliant diamonds weighing a total of approximately 0.07 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856730/11_pkei2s.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856730/12_wuy4n5.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/38_l5one6.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/37_vxepl2.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/63_ottakt.avif',
        'primary_stone': 'BS',
        'reference': 'STU',
        'stones': ['DI', 'SA'],
        'price': 4500,
    },
    # pendants
    {
        'category': 'NE',
        'collection': 'FO',
        'colors': ['WH'],
        'description': '6 pear-shaped and 1 round brilliant diamond weighing a total of approximately 1.07 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856725/19_qvdzj7.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856725/20_hhtxfz.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/38_l5one6.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/37_vxepl2.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/63_ottakt.avif',
        'primary_stone': 'WD',
        'reference': 'PE',
        'stones': ['DI'],
        'price': 7700,
    },
    {
        'category': 'NE',
        'collection': 'FO',
        'colors': ['WH', 'PI'],
        'description': '6 pear-shaped pink sapphires weighing a total of approximately 1.44 carats and 1 round brilliant diamond weighing approximately 0.04 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856726/21_ekvmgg.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856727/22_tzvvcv.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/38_l5one6.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/37_vxepl2.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/63_ottakt.avif',
        'primary_stone': 'PS',
        'reference': 'PE',
        'stones': ['DI', 'SA'],
        'price': 7500,
    },
    {
        'category': 'NE',
        'collection': 'FO',
        'colors': ['WH', 'BL'],
        'description': '6 pear-shaped sapphires weighing a total of approximately 1.41 carats and 1 round brilliant diamond weighing approximately 0.04 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856726/23_iwaai6.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856726/24_sqx9h1.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/38_l5one6.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/37_vxepl2.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/63_ottakt.avif',
        'primary_stone': 'BS',
        'reference': 'PE',
        'stones': ['DI', 'SA'],
        'price': 7500,
    },
    {
        'category': 'NE',
        'collection': 'FO',
        'colors': ['WH', 'RE'],
        'description': '6 pear-shaped rubies weighing a total of approximately 1.68 carats and 1 round brilliant diamond weighing a total of approximately 0.04 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856726/39_jrwngf.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856725/40_juxvhh.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/38_l5one6.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/37_vxepl2.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/63_ottakt.avif',
        'primary_stone': 'RU',
        'reference': 'PE',
        'stones': ['DI', 'RU'],
        'price': 7600,
    },
    {
        'category': 'NE',
        'collection': 'FO',
        'colors': ['WH'],
        'description': '177 pear-shaped, marquise, and round brilliant diamonds, weighing a total of approximately 15.35 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856727/25_oqbvq3.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856727/26_gnnsd4.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/38_l5one6.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/37_vxepl2.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/63_ottakt.avif',
        'primary_stone': 'WD',
        'reference': 'LA',
        'stones': ['DI'],
        'price': 9800,
    },
    {
        'category': 'NE',
        'collection': 'FO',
        'colors': ['WH', 'PI'],
        'description': '78 pear-shaped and round brilliant pink sapphires weighing a total of approximately 8.61 carats and 99 marquise and round brilliant diamonds weighing a total of approximately 8.60 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856729/27_i1bprh.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856729/28_ro5rxy.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/38_l5one6.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/37_vxepl2.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/63_ottakt.avif',
        'primary_stone': 'PS',
        'reference': 'LA',
        'stones': ['DI', 'SA'],
        'price': 9500,
    },
    {
        'category': 'NE',
        'collection': 'FO',
        'colors': ['WH', 'BL'],
        'description': '78 pear-shaped and round brilliant sapphires weighing a total of approximately 8.61 carats and 99 marquise and round brilliant diamonds weighing a total of approximately 8.37 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856728/29_efdhpn.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856728/30_zmf8x5.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/38_l5one6.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/37_vxepl2.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/63_ottakt.avif',
        'primary_stone': 'BS',
        'reference': 'LA',
        'stones': ['DI', 'SA'],
        'price': 9500,
    },
    {
        'category': 'NE',
        'collection': 'FO',
        'colors': ['WH', 'RE'],
        'description': '78 pear-shaped and round rubies weighing a total of approximately 9.13 carats and 99 marquise and round brilliant diamonds weighing a total of approximately 8.51 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856728/50_cox6xw.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856727/60_n2uukj.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/38_l5one6.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/37_vxepl2.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/63_ottakt.avif',
        'primary_stone': 'RU',
        'reference': 'LA',
        'stones': ['DI', 'RU'],
        'price': 9600,
    },
    # rings
    {
        'category': 'RI',
        'collection': 'FO',
        'colors': ['WH', 'BL'],
        'description': '6 pear-shaped sapphires weighing a total of approximately 2.15 carats and 1 round brilliant diamond weighing approximately 0.05 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/31_mh5xwc.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/32_o1zcqo.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/38_l5one6.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/37_vxepl2.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/63_ottakt.avif',
        'primary_stone': 'BS',
        'reference': 'LA',
        'stones': ['DI', 'SA'],
        'price': 4000,
    },
    {
        'category': 'RI',
        'collection': 'FO',
        'colors': ['WH'],
        'description': '6 pear-shaped and 1 round brilliant diamond, weighing a total of approximately 1.66 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856724/33_zrcek3.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856724/34_jbcbau.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/38_l5one6.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/37_vxepl2.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/63_ottakt.avif',
        'primary_stone': 'WD',
        'reference': 'STA',
        'stones': ['DI'],
        'price': 4200,
    },
    {
        'category': 'RI',
        'collection': 'FO',
        'colors': ['WH', 'PI'],
        'description': '6 pear-shaped pink sapphires weighing a total of approximately 2.22 carats and 1 round brilliant diamond weighing approximately 0.05 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/35_xcx85g.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856724/36_hlqb5d.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856723/38_l5one6.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856720/37_vxepl2.avif',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856722/63_ottakt.avif',
        'primary_stone': 'PS',
        'reference': 'STA',
        'stones': ['DI', 'SA'],
        'price': 4200,
    },
    # GERBERA DAISY
    # bracelets
    {
        'category': 'BR',
        'collection': 'GE',
        'colors': ['WI'],
        'description': '29 round brilliant diamonds weighing a total of approximately 0.29 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856733/7_yopjx2.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856734/8_nnmrem.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/sbs_pdp_winstongates_eoosbz.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856733/373107_abdcs8.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/herolarged_pdp_winstongates_sxltqh.jpg',
        'primary_stone': 'WD',
        'reference': 'CH',
        'stones': ['DI'],
        'price': 3700,
    },
    {
        'category': 'BR',
        'collection': 'GE',
        'colors': ['WI'],
        'description': '29 round brilliant diamonds weighing a total of approximately 0.29 carats, set in 18K yellow gold.',
        'materials': ['YE'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/9_meqctb.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/10_wufmzy.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/sbs_pdp_winstongates_eoosbz.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856733/373107_abdcs8.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/herolarged_pdp_winstongates_sxltqh.jpg',
        'primary_stone': 'WD',
        'reference': 'CH',
        'stones': ['DI'],
        'price': 3500,
    },
    {
        'category': 'BR',
        'collection': 'GE',
        'colors': ['WI'],
        'description': '29 round brilliant diamonds weighing a total of approximately 0.29 carats, set in 18K rose gold.',
        'materials': ['RO'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856734/11_vkbeky.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856734/12_tjzjkt.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/sbs_pdp_winstongates_eoosbz.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856733/373107_abdcs8.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/herolarged_pdp_winstongates_sxltqh.jpg',
        'primary_stone': 'WD',
        'reference': 'CH',
        'stones': ['DI'],
        'price': 3500,
    },
    # earrings
    {
        'category': 'EA',
        'collection': 'GE',
        'colors': ['WI'],
        'description': '58 round brilliant diamonds weighing a total of approximately 0.43 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856739/19_vjeigd.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856739/20_vc8sus.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/sbs_pdp_winstongates_eoosbz.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856733/373107_abdcs8.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/herolarged_pdp_winstongates_sxltqh.jpg',
        'primary_stone': 'WD',
        'reference': 'STU',
        'stones': ['DI'],
        'price': 3100,
    },
    {
        'category': 'EA',
        'collection': 'GE',
        'colors': ['WI'],
        'description': '58 round brilliant diamonds weighing a total of approximately 0.43 carats, set in 18K yellow gold.',
        'materials': ['YE'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856741/21_uxbxeb.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856740/22_sd9e4h.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/sbs_pdp_winstongates_eoosbz.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856733/373107_abdcs8.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/herolarged_pdp_winstongates_sxltqh.jpg',
        'primary_stone': 'WD',
        'reference': 'STU',
        'stones': ['DI'],
        'price': 3000,
    },
    {
        'category': 'EA',
        'collection': 'GE',
        'colors': ['WI'],
        'description': '58 round brilliant diamonds weighing a total of approximately 0.43 carats, set in 18K rose gold.',
        'materials': ['RS'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856740/23_quvkpx.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856740/24_viti3i.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/sbs_pdp_winstongates_eoosbz.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856733/373107_abdcs8.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/herolarged_pdp_winstongates_sxltqh.jpg',
        'primary_stone': 'WD',
        'reference': 'STU',
        'stones': ['DI'],
        'price': 3000,
    },
    # necklaces
    {
        'category': 'NE',
        'collection': 'GE',
        'colors': ['WI'],
        'description': '29 round brilliant diamonds weighing a total of approximately 0.29 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856738/1_szzi1c.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856737/2_hzextj.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/sbs_pdp_winstongates_eoosbz.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856733/373107_abdcs8.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/herolarged_pdp_winstongates_sxltqh.jpg',
        'primary_stone': 'WD',
        'reference': 'PE',
        'stones': ['DI'],
        'price': 4200,
    },
    {
        'category': 'NE',
        'collection': 'GE',
        'colors': ['WI'],
        'description': '29 round brilliant diamonds weighing a total of approximately 0.29 carats, set in 18K yellow gold.',
        'materials': ['YE'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856739/3_wupysj.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856739/4_k9a4uv.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/sbs_pdp_winstongates_eoosbz.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856733/373107_abdcs8.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/herolarged_pdp_winstongates_sxltqh.jpg',
        'primary_stone': 'WD',
        'reference': 'PE',
        'stones': ['DI'],
        'price': 4000,
    },
    {
        'category': 'NE',
        'collection': 'GE',
        'colors': ['WI'],
        'description': '29 round brilliant diamonds weighing a total of approximately 0.29 carats, set in 18K rose gold.',
        'materials': ['RO'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856738/5_rrlmoe.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856738/6_iackza.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/sbs_pdp_winstongates_eoosbz.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856733/373107_abdcs8.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/herolarged_pdp_winstongates_sxltqh.jpg',
        'primary_stone': 'WD',
        'reference': 'PE',
        'stones': ['DI'],
        'price': 4000,
    },
    # rings
    {
        'category': 'RI',
        'collection': 'GE',
        'colors': ['WI'],
        'description': '31 round brilliant diamonds weighing a total of approximately 0.40 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856737/13_xgwtpr.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856736/14_kqxkvo.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/sbs_pdp_winstongates_eoosbz.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856733/373107_abdcs8.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/herolarged_pdp_winstongates_sxltqh.jpg',
        'primary_stone': 'WD',
        'reference': 'RI',
        'stones': ['DI'],
        'price': 3600,
    },
    {
        'category': 'RI',
        'collection': 'GE',
        'colors': ['WI'],
        'description': '31 round brilliant diamonds weighing a total of approximately 0.40 carats, set in 18K yellow gold.',
        'materials': ['YE'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856736/15_rekqju.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856736/15_rekqju.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/sbs_pdp_winstongates_eoosbz.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856733/373107_abdcs8.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/herolarged_pdp_winstongates_sxltqh.jpg',
        'primary_stone': 'WD',
        'reference': 'STA',
        'stones': ['DI'],
        'price': 3400,
    },
    {
        'category': 'RI',
        'collection': 'GE',
        'colors': ['WI'],
        'description': '31 round brilliant diamonds weighing a total of approximately 0.40 carats, set in 18K rose gold.',
        'materials': ['YE'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856736/17_t26gka.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856736/18_jqpfrr.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/sbs_pdp_winstongates_eoosbz.jpg',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856733/373107_abdcs8.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856735/herolarged_pdp_winstongates_sxltqh.jpg',
        'primary_stone': 'WD',
        'reference': 'STA',
        'stones': ['DI'],
        'price': 3400,
    },
    # LILY BLOOM
    # bracelets
    {
        'category': 'BR',
        'collection': 'LI',
        'colors': ['WH'],
        'description': '75 round brilliant diamonds set in warm 18k yellow gold, this timeless piece captures one of nature’s most beautiful blooms.',
        'materials': ['YE'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856742/1_anxylk.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/2_z9ntu6.png',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856741/lily24_pdp_b_3_akkd7v.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/lily24_pdp_c_e1ihow.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/28_mqzog7.avif',
        'primary_stone': 'WD',
        'reference': 'CH',
        'stones': ['DI'],
        'price': 3000,
    },
    {
        'category': 'BR',
        'collection': 'LI',
        'colors': ['WH'],
        'description': '75 round brilliant diamonds, each masterfully set in lustrous platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856741/5_wcemq4.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856742/6_tkfzty.png',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856741/lily24_pdp_b_3_akkd7v.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/lily24_pdp_c_e1ihow.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/28_mqzog7.avif',
        'primary_stone': 'WD',
        'reference': 'CH',
        'stones': ['DI'],
        'price': 3200,
    },
    {
        'category': 'BR',
        'collection': 'LI',
        'colors': ['WH'],
        'description': '47 round brilliant diamonds weighing a total of approximately 0.31 carats, set in 18K rose gold. ',
        'materials': ['RO'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856741/3_zafs4t.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856742/4_jbijwg.png',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856741/lily24_pdp_b_3_akkd7v.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/lily24_pdp_c_e1ihow.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/28_mqzog7.avif',
        'primary_stone': 'WD',
        'reference': 'CH',
        'stones': ['DI'],
        'price': 3200,
    },
    # necklaces
    {
        'category': 'NE',
        'collection': 'LI',
        'colors': ['WH'],
        'description': '1 marquise and 45 round brilliant diamonds weighing a total of approximately 0.68 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856746/12_bdrupe.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856746/13_fe4z7n.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856741/lily24_pdp_b_3_akkd7v.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/lily24_pdp_c_e1ihow.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/28_mqzog7.avif',
        'primary_stone': 'WD',
        'reference': 'PE',
        'stones': ['DI'],
        'price': 3700,
    },
    {
        'category': 'NE',
        'collection': 'LI',
        'colors': ['WH'],
        'description': '1 marquise and 45 round brilliant diamonds weighing a total of approximately 0.68 carats, set in 18K yellow gold.',
        'materials': ['YE'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857651/14_wlqhbf.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857651/15_xbyed3.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856741/lily24_pdp_b_3_akkd7v.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/lily24_pdp_c_e1ihow.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/28_mqzog7.avif',
        'primary_stone': 'WD',
        'reference': 'PE',
        'stones': ['DI'],
        'price': 3500,
    },
    {
        'category': 'NE',
        'collection': 'LI',
        'colors': ['WH'],
        'description': '1 marquise and 45 round brilliant diamonds weighing a total of approximately 0.68 carats, set in 18K rose gold.',
        'materials': ['RO'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857651/16_m4ae1k.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856791/17_ywdinc.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856741/lily24_pdp_b_3_akkd7v.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/lily24_pdp_c_e1ihow.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/28_mqzog7.avif',
        'primary_stone': 'WD',
        'reference': 'PE',
        'stones': ['DI'],
        'price': 3500,
    },
    {
        'category': 'NE',
        'collection': 'LI',
        'colors': ['WH'],
        'description': '619 round brilliant diamonds weighing a total of approximately 5.33 carats, set in 18K yellow gold.',
        'materials': ['YE'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857652/24_lt0t4w.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857652/25_o5odgo.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856741/lily24_pdp_b_3_akkd7v.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/lily24_pdp_c_e1ihow.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/28_mqzog7.avif',
        'primary_stone': 'WD',
        'reference': 'LA',
        'stones': ['DI'],
        'price': 4500,
    },
    {
        'category': 'NE',
        'collection': 'LI',
        'colors': ['WH'],
        'description': '619 round brilliant diamonds weighing a total of approximately 5.33 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857652/26_xp6skd.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745857653/27_jnubbq.webp',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856741/lily24_pdp_b_3_akkd7v.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/lily24_pdp_c_e1ihow.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/28_mqzog7.avif',
        'primary_stone': 'WD',
        'reference': 'LA',
        'stones': ['DI'],
        'price': 4700,
    },
    # rings
    {
        'category': 'RI',
        'collection': 'LI',
        'colors': ['WH'],
        'description': '1 marquise and 54 round brilliant diamonds weighing a total of approximately 0.41 carats, set in platinum.',
        'materials': ['PL'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856744/18_i6mhsa.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856744/19_rkivut.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856741/lily24_pdp_b_3_akkd7v.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/lily24_pdp_c_e1ihow.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/28_mqzog7.avif',
        'primary_stone': 'WD',
        'reference': 'STA',
        'stones': ['DI'],
        'price': 2700,
    },
    {
        'category': 'RI',
        'collection': 'LI',
        'colors': ['WH'],
        'description': '1 marquise and 54 round brilliant diamonds weighing a total of approximately 0.41 carats, set in 18k yellow gold.',
        'materials': ['YE'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856745/20_aahcgy.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856745/21_bgldka.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856741/lily24_pdp_b_3_akkd7v.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/lily24_pdp_c_e1ihow.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/28_mqzog7.avif',
        'primary_stone': 'WD',
        'reference': 'STA',
        'stones': ['DI'],
        'price': 2500,
    },
    {
        'category': 'RI',
        'collection': 'LI',
        'colors': ['WH'],
        'description': '1 marquise and 54 round brilliant diamonds weighing a total of approximately 0.41 carats, set in 18K rose gold.',
        'materials': ['RO'],
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856745/22_zdywno.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856747/23_f6ywtz.avif',
        'third_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856741/lily24_pdp_b_3_akkd7v.png',
        'fourth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/lily24_pdp_c_e1ihow.jpg',
        'fifth_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745856743/28_mqzog7.avif',
        'primary_stone': 'WD',
        'reference': 'STA',
        'stones': ['DI'],
        'price': 2500,
    },
    # RADIANT CLUSTER
]
