stones_colors = {
    'Aquamarine Aquamarine': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745748232/aquamarine_b4dtyx.webp',
    'White Diamond': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745748236/diamond_dkg8rb.webp',
    'Yellow Diamond': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745853383/brown-diamond-CD_xvzlf6.webp',
    'Green Emerald': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745748237/emerald_auiwk4.webp',
    'Red Ruby': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745748233/ruby_g7idgx.webp',
    'Blue Sapphire': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745748233/blue-sapphire_bjwmoo.webp',
    'Pink Sapphire': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745748232/pink-sapphire_se5pnk.webp',
    'Yellow Sapphire': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1745853383/yellow-sapphire_tukm7x.webp',
}


{
    'category': '',
    'collection': '',
    'material': '',
    'first_image': '',
    'second_image': '',
    'reference': '',
    'stones_colors': [],
    'price': 0,
},


products_data = [
    # BERRY
    {
        'category': 'Earring',
        'collection': 'Berry',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115862/9_zuupv7.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115868/10_ccqces.webp',
        'reference': 'Stud',
        'stones_colors': ['White Diamond', 'Blue Sapphire'],
        'price': 3600,
    },
    {
        'category': 'Earring',
        'collection': 'Berry',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115870/7_oxmuys.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115867/8_k1zqeq.webp',
        'reference': 'Stud',
        'stones_colors': ['White Diamond', 'Red Ruby'],
        'price': 3700,
    },
    {
        'category': 'Earring',
        'collection': 'Berry',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115868/11_ntbstg.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115867/12_re58tf.webp',
        'reference': 'Stud',
        'stones_colors': ['White Diamond', 'Green Emerald'],
        'price': 3400,
    },
    {
        'category': 'Necklace',
        'collection': 'Berry',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115862/5_rlufar.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115867/6_cb1tab.avif',
        'reference': 'Pendant',
        'stones_colors': ['White Diamond', 'Green Emerald'],
        'price': 4400,
    },
    {
        'category': 'Necklace',
        'collection': 'Berry',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115867/3_bhkuqr.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115870/4_pbumhb.avif',
        'reference': 'Pendant',
        'stones_colors': ['White Diamond', 'Blue Sapphire'],
        'price': 4600,
    },
    {
        'category': 'Necklace',
        'collection': 'Berry',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115868/1_rcfsir.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115870/2_vf7yxw.avif',
        'reference': 'Pendant',
        'stones_colors': ['White Diamond', 'Red Ruby'],
        'price': 4800,
    },
    {
        'category': 'Ring',
        'collection': 'Berry',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115867/16_rkceku.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115868/15.avif_fmwmjz.png',
        'reference': 'Band',
        'stones_colors': ['White Diamond', 'Red Ruby'],
        'price': 2800,
    },
    {
        'category': 'Ring',
        'collection': 'Berry',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115867/14_jaiuit.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115870/13.avif_hc7tnh.png',
        'reference': 'Band',
        'stones_colors': ['White Diamond', 'Blue Sapphire'],
        'price': 2600,
    },
    # FORGET ME NOT
    {
        'category': 'Bracelet',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115880/37_yydycy.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115884/38_ebclnr.avif',
        'reference': 'Tennis',
        'stones_colors': ['White Diamond', 'Blue Sapphire'],
        'price': 5200,
    },
    {
        'category': 'Bracelet',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115880/35_tl8ef4.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115874/36_vypeqm.avif',
        'reference': 'Tennis',
        'stones_colors': ['White Diamond', 'Red Ruby'],
        'price': 5400,
    },
    {
        'category': 'Bracelet',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115880/39_ec0wun.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115871/40_jh7chy.avif',
        'reference': 'Tennis',
        'stones_colors': ['White Diamond', 'Pink Sapphire'],
        'price': 5100,
    },
    {
        'category': 'Earring',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115871/19_cp3mbf.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115883/20_iumckw.webp',
        'reference': 'Stud',
        'stones_colors': ['White Diamond', 'Pink Sapphire'],
        'price': 3800,
    },
    {
        'category': 'Earring',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115870/15_wi6mrj.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115883/16_ujqqh5.webp',
        'reference': 'Stud',
        'stones_colors': ['White Diamond'],
        'price': 4100,
    },
    {
        'category': 'Earring',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115880/17_ej3xxw.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115874/18_xdy6cx.webp',
        'reference': 'Stud',
        'stones_colors': ['White Diamond', 'Blue Sapphire'],
        'price': 3800,
    },
    {
        'category': 'Earring',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115876/25_ohyxwk.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115879/26_ncvot1.webp',
        'reference': 'Drop',
        'stones_colors': ['White Diamond', 'Pink Sapphire'],
        'price': 4800,
    },
    {
        'category': 'Earring',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115873/23_xi7kdz.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115876/24_mlbxu2.webp',
        'reference': 'Drop',
        'stones_colors': ['White Diamond', 'Blue Sapphire'],
        'price': 4800,
    },
    {
        'category': 'Earring',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115880/21_sspkef.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115873/22_u9duuz.webp',
        'reference': 'Drop',
        'stones_colors': ['White Diamond'],
        'price': 5100,
    },
    {
        'category': 'Necklace',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115871/7_bxav8b.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115882/8_udhrsq.avif',
        'reference': 'Pendant',
        'stones_colors': ['White Diamond', 'Pink Sapphire'],
        'price': 6700,
    },
    {
        'category': 'Necklace',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115871/5_tstc0a.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115874/6_yegbsi.avif',
        'reference': 'Pendant',
        'stones_colors': ['White Diamond', 'Blue Sapphire'],
        'price': 6700,
    },
    {
        'category': 'Necklace',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115876/3_ovmsps.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115874/4_gyndsx.webp',
        'reference': 'Pendant',
        'stones_colors': ['White Diamond'],
        'price': 7000,
    },
    {
        'category': 'Necklace',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115877/1_20.58.26_rzrysl.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115877/2_20.58.26_zij1ov.avif',
        'reference': 'Pendant',
        'stones_colors': ['White Diamond', 'Red Ruby'],
        'price': 6800,
    },
    {
        'category': 'Necklace',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115874/33_ctp104.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115874/34_chlsa5.webp',
        'reference': 'Lariat',
        'stones_colors': ['White Diamond', 'Pink Sapphire'],
        'price': 8400,
    },
    {
        'category': 'Necklace',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115876/31_qt3bmf.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115879/32_odt4pf.avif',
        'reference': 'Lariat',
        'stones_colors': ['White Diamond', 'Blue Sapphire'],
        'price': 8400,
    },
    {
        'category': 'Necklace',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115877/29_hxlfiw.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115879/30_wyt89z.webp',
        'reference': 'Lariat',
        'stones_colors': ['White Diamond'],
        'price': 8700,
    },
    {
        'category': 'Necklace',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115876/27_mz3g3o.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115879/28_ecki0c.avif',
        'reference': 'Lariat',
        'stones_colors': ['White Diamond', 'Red Ruby'],
        'price': 8500,
    },
    {
        'category': 'Ring',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115876/13_jvc89m.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115883/14_ryucup.avif',
        'reference': 'Statement',
        'stones_colors': ['White Diamond', 'Pink Sapphire'],
        'price': 4400,
    },
    {
        'category': 'Ring',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115876/11_kmd9oy.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115879/12_khumxz.avif',
        'reference': 'Statement',
        'stones_colors': ['White Diamond', 'Blue Sapphire'],
        'price': 4400,
    },
    {
        'category': 'Ring',
        'collection': 'Forget Me Not',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115873/9_pfybkq.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115878/10_fcq7yp.webp',
        'reference': 'Statement',
        'stones_colors': ['White Diamond'],
        'price': 4600,
    },
    # GERBERA
    {
        'category': 'Bracelet',
        'collection': 'Gerbera',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115898/7_dyy0ui.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115903/8_nb7rfa.avif',
        'reference': 'Chain',
        'stones_colors': ['White Diamond'],
        'price': 3400,
    },
    {
        'category': 'Bracelet',
        'collection': 'Gerbera',
        'material': 'Rose Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115897/11_fnhj5z.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115897/12_c4gztu.avif',
        'reference': 'Chain',
        'stones_colors': ['White Diamond'],
        'price': 3200,
    },
    {
        'category': 'Bracelet',
        'collection': 'Gerbera',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115890/9_hgiify.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115892/10_lbk6i1.avif',
        'reference': 'Chain',
        'stones_colors': ['White Diamond'],
        'price': 3200,
    },
    {
        'category': 'Earring',
        'collection': 'Gerbera',
        'material': 'Rose Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115890/23_riwfc0.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115892/24_sodzvz.webp',
        'reference': 'Stud',
        'stones_colors': ['White Diamond'],
        'price': 1600,
    },
    {
        'category': 'Earring',
        'collection': 'Gerbera',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115898/21_o5ytzr.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115892/22_y8mhmh.webp',
        'reference': 'Stud',
        'stones_colors': ['White Diamond'],
        'price': 1600,
    },
    {
        'category': 'Earring',
        'collection': 'Gerbera',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115890/19_yq40yi.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115903/20_lsunqd.webp',
        'reference': 'Stud',
        'stones_colors': ['White Diamond'],
        'price': 1900,
    },
    {
        'category': 'Necklace',
        'collection': 'Gerbera',
        'material': 'Rose Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115898/5_ltcjn8.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115892/6_aj31h8.avif',
        'reference': 'Pendant',
        'stones_colors': ['White Diamond'],
        'price': 2600,
    },
    {
        'category': 'Necklace',
        'collection': 'Gerbera',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115893/3_nfudoh.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115904/4_jgqw79.avif',
        'reference': 'Pendant',
        'stones_colors': ['White Diamond'],
        'price': 2600,
    },
    {
        'category': 'Necklace',
        'collection': 'Gerbera',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115892/1_mxaw0n.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115897/2_jbpdul.avif',
        'reference': 'Pendant',
        'stones_colors': ['White Diamond'],
        'price': 2900,
    },
    {
        'category': 'Ring',
        'collection': 'Gerbera',
        'material': 'Rose Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115898/17_sve1ov.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115892/18_mk2aen.webp',
        'reference': 'Statement',
        'stones_colors': ['White Diamond'],
        'price': 1900,
    },
    {
        'category': 'Ring',
        'collection': 'Gerbera',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115889/15_vhtm13.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115904/16_oungz5.webp',
        'reference': 'Statement',
        'stones_colors': ['White Diamond'],
        'price': 1900,
    },
    {
        'category': 'Ring',
        'collection': 'Gerbera',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115892/13_c91ddg.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115892/14_khi7ft.webp',
        'reference': 'Statement',
        'stones_colors': ['White Diamond'],
        'price': 2100,
    },
    # LEAF
    {
        'category': 'Necklace',
        'collection': 'Leaf',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115848/3_eqrpuo.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115848/4_zdqfzb.avif',
        'reference': 'Pendant',
        'stones_colors': ['White Diamond'],
        'price': 3300,
    },
    {
        'category': 'Necklace',
        'collection': 'Leaf',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115848/1_y1wtvj.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115847/2_csala1.avif',
        'reference': 'Pendant',
        'stones_colors': ['White Diamond'],
        'price': 3500,
    },
    {
        'category': 'Necklace',
        'collection': 'Leaf',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115848/9_cglk2f.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115849/10_yaxfhs.webp',
        'reference': 'Lariat',
        'stones_colors': ['White Diamond'],
        'price': 4300,
    },
    {
        'category': 'Necklace',
        'collection': 'Leaf',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115848/11_mvguf6.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115848/12_vv0hw2.avif',
        'reference': 'Lariat',
        'stones_colors': ['White Diamond'],
        'price': 4100,
    },
    {
        'category': 'Ring',
        'collection': 'Leaf',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115847/5_mbpwau.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115849/6_tma5f6.webp',
        'reference': 'Statement',
        'stones_colors': ['White Diamond'],
        'price': 2700,
    },
    {
        'category': 'Ring',
        'collection': 'Leaf',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115848/7_u3mjub.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115848/8_admfwl.avif',
        'reference': 'Statement',
        'stones_colors': ['White Diamond'],
        'price': 2400,
    },
    # LILY
    {
        'category': 'Bracelet',
        'collection': 'Lily',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115861/3_z0khec.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115862/4_yomnun.avif',
        'reference': 'Chain',
        'stones_colors': ['White Diamond'],
        'price': 2900,
    },
    {
        'category': 'Bracelet',
        'collection': 'Lily',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115861/1_ra0at7.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115862/2_qtaybi.avif',
        'reference': 'Chain',
        'stones_colors': ['White Diamond'],
        'price': 3100,
    },
    {
        'category': 'Necklace',
        'collection': 'Lily',
        'material': 'Rose Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115856/7_kkhuqt.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115862/8_fn8lmj.avif',
        'reference': 'Pendant',
        'stones_colors': ['White Diamond'],
        'price': 4000,
    },
    {
        'category': 'Necklace',
        'collection': 'Lily',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115862/5_jg8e9x.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115861/6_viukk8.avif',
        'reference': 'Pendant',
        'stones_colors': ['White Diamond'],
        'price': 4000,
    },
    {
        'category': 'Ring',
        'collection': 'Lily',
        'material': 'Yellow Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115862/9_ug9qjk.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115861/10_kvifdt.avif',
        'reference': 'Statement',
        'stones_colors': ['White Diamond'],
        'price': 2400,
    },
    {
        'category': 'Ring',
        'collection': 'Lily',
        'material': 'Rose Gold',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115861/11_qwmmry.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115861/12_wykwod.avif',
        'reference': 'Statement',
        'stones_colors': ['White Diamond'],
        'price': 2400,
    },
    # Lily of the Valley
    {
        'category': 'Earring',
        'collection': 'Lily of the Valley',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115885/9_nrvzgx.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115886/10_gbgzq4.webp',
        'reference': 'Drop',
        'stones_colors': ['White Diamond'],
        'price': 5500,
    },
    {
        'category': 'Earring',
        'collection': 'Lily of the Valley',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115886/1_zaesmv.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115886/2_omxh92.webp',
        'reference': 'Drop',
        'stones_colors': ['White Diamond', 'Aquamarine Aquamarine', 'Blue Sapphire'],
        'price': 5200,
    },
    {
        'category': 'Necklace',
        'collection': 'Lily of the Valley',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115884/5_azojfd.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115889/6_xefvoj.webp',
        'reference': 'Pendant',
        'stones_colors': ['White Diamond', 'Aquamarine Aquamarine', 'Blue Sapphire'],
        'price': 7100,
    },
    {
        'category': 'Necklace',
        'collection': 'Lily of the Valley',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115889/14_rmtgtc.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115884/15_gbcgxu.webp',
        'reference': 'Pendant',
        'stones_colors': ['White Diamond'],
        'price': 7900,
    },
    {
        'category': 'Necklace',
        'collection': 'Lily of the Valley',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115889/16_ghdpy4.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115889/17_pzsxrr.webp',
        'reference': 'Lariat',
        'stones_colors': ['White Diamond'],
        'price': 9100,
    },
    {
        'category': 'Necklace',
        'collection': 'Lily of the Valley',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115889/7_mflsat.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115889/8_z0yovn.avif',
        'reference': 'Lariat',
        'stones_colors': ['White Diamond',  'Aquamarine Aquamarine', 'Blue Sapphire'],
        'price': 8800,
    },
    {
        'category': 'Ring',
        'collection': 'Lily of the Valley',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115886/3_onvsdq.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115885/4_k2z9sm.webp',
        'reference': 'Statement',
        'stones_colors': ['White Diamond',  'Aquamarine Aquamarine', 'Blue Sapphire'],
        'price': 4900,
    },
    {
        'category': 'Ring',
        'collection': 'Lily of the Valley',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115885/11_gxtusc.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115886/12_cyplba.webp',
        'reference': 'Statement',
        'stones_colors': ['White Diamond'],
        'price': 5200,
    },
    # LOTUS
    {
        'category': 'Earring',
        'collection': 'Lotus',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115849/5_akqszw.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115855/6_p1hv03.webp',
        'reference': 'Stud',
        'stones_colors': ['White Diamond', 'Green Emerald'],
        'price': 6200,
    },
    {
        'category': 'Earring',
        'collection': 'Lotus',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115854/3_pwfqbd.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115855/4_zvx63m.avif',
        'reference': 'Stud',
        'stones_colors': ['White Diamond', 'Blue Sapphire'],
        'price': 6400,
    },
    {
        'category': 'Earring',
        'collection': 'Lotus',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115854/1_dthftn.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115850/2_no2d0x.webp',
        'reference': 'Stud',
        'stones_colors': ['White Diamond', 'Red Ruby'],
        'price': 6600,
    },
    {
        'category': 'Necklace',
        'collection': 'Lotus',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115849/9_elxmpl.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115850/10_v5sj9r.avif',
        'reference': 'Pendant',
        'stones_colors': ['White Diamond', 'Red Ruby'],
        'price': 7600,
    },
    {
        'category': 'Necklace',
        'collection': 'Lotus',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115849/7_kfghke.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115855/8_w3dnks.avif',
        'reference': 'Pendant',
        'stones_colors': ['White Diamond', 'Pink Sapphire'],
        'price': 7400,
    },
    {
        'category': 'Necklace',
        'collection': 'Lotus',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115854/13_shljw5.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115855/14_yj8tc1.avif',
        'reference': 'Pendant',
        'stones_colors': ['White Diamond', 'Green Emerald'],
        'price': 7200,
    },
    {
        'category': 'Necklace',
        'collection': 'Lotus',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115854/11_grxxeo.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115854/12_qty9ix.avif',
        'reference': 'Pendant',
        'stones_colors': ['White Diamond', 'Blue Sapphire'],
        'price': 7400,
    },
    {
        'category': 'Ring',
        'collection': 'Lotus',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115855/17_txm6ur.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115849/18_othoqv.webp',
        'reference': 'Statement',
        'stones_colors': ['White Diamond', 'Blue Sapphire'],
        'price': 5200,
    },
    {
        'category': 'Ring',
        'collection': 'Lotus',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115855/15_jxzwza.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115850/16_fmv4dv.avif',
        'reference': 'Statement',
        'stones_colors': ['White Diamond', 'Red Ruby'],
        'price': 5400,
    },
    # SUNFLOWER
    {
        'category': 'Earring',
        'collection': 'Sunflower',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115904/9_sqhg38.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115904/10_iv9a0s.avif',
        'reference': 'Stud',
        'stones_colors': ['White Diamond', 'Red Ruby'],
        'price': 2100,
    },
    {
        'category': 'Earring',
        'collection': 'Sunflower',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115907/7_biz36z.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115904/8_bnvuri.webp',
        'reference': 'Stud',
        'stones_colors': ['White Diamond', 'Blue Sapphire'],
        'price': 1900,
    },
    {
        'category': 'Earring',
        'collection': 'Sunflower',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115904/5_tdbnmb.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115907/6_hqhraj.webp',
        'reference': 'Stud',
        'stones_colors': ['White Diamond'],
        'price': 2200,
    },
    {
        'category': 'Ring',
        'collection': 'Sunflower',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115907/13_b96r6b.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115907/14_upeut9.avif',
        'reference': 'Statement',
        'stones_colors': ['White Diamond', 'Red Ruby'],
        'price': 3300,
    },
    {
        'category': 'Ring',
        'collection': 'Sunflower',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115904/11_gzogqa.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746115907/12_lxtshr.avif',
        'reference': 'Statement',
        'stones_colors': ['White Diamond'],
        'price': 3100,
    },
    # Daisy
    {
        'category': 'Earring',
        'collection': 'Daisy',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121005/9_sciejy.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121016/10_darmna.webp',
        'reference': 'Stud',
        'stones_colors': ['White Diamond', 'Pink Sapphire'],
        'price': 1500,
    },
    {
        'category': 'Earring',
        'collection': 'Daisy',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121145/7_nvuh9g.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121006/8_bhttl1.webp',
        'reference': 'Stud',
        'stones_colors': ['White Diamond', 'Red Ruby'],
        'price': 1700,
    },
    {
        'category': 'Earring',
        'collection': 'Daisy',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121009/13_mjvoux.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121008/14_rvbedu.webp',
        'reference': 'Stud',
        'stones_colors': ['White Diamond', 'Yellow Sapphire'],
        'price': 1500,
    },
    {
        'category': 'Earring',
        'collection': 'Daisy',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121010/11_momftr.avif',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121013/12_ou80ul.webp',
        'reference': 'Stud',
        'stones_colors': ['White Diamond', 'Aquamarine Aquamarine'],
        'price': 1500,
    },
    {
        'category': 'Necklace',
        'collection': 'Daisy',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121005/5_mvon0h.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121006/6_hr6odl.avif',
        'reference': 'Pendant',
        'stones_colors': ['White Diamond', 'Yellow Sapphire'],
        'price': 4400,
    },
    {
        'category': 'Necklace',
        'collection': 'Daisy',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121011/3_uskksz.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121262/4_cetexv.avif',
        'reference': 'Pendant',
        'stones_colors': ['White Diamond', 'Aquamarine Aquamarine'],
        'price': 4400,
    },
    {
        'category': 'Necklace',
        'collection': 'Daisy',
        'material': 'Platinum',
        'first_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121014/1_hgm4vf.webp',
        'second_image': 'https://res.cloudinary.com/dpgvbozrb/image/upload/v1746121261/2_t5lujx.avif',
        'reference': 'Pendant',
        'stones_colors': ['White Diamond', 'Pink Sapphire'],
        'price': 4400,
    },

]
