# Generated by Django 5.2.1 on 2025-05-28 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_fingerwearsize_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fingerwearinventory',
            options={'ordering': ['size__id']},
        ),
        migrations.AlterModelOptions(
            name='neckwearinventory',
            options={'ordering': ['size__id']},
        ),
        migrations.AlterModelOptions(
            name='wristwearinventory',
            options={'ordering': ['size__id']},
        ),
    ]
