# Generated by Django 5.2.1 on 2025-07-10 18:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shopping_bags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoppingbag',
            unique_together={('guest_id', 'content_type', 'object_id'), ('user', 'content_type', 'object_id')},
        ),
    ]
