# Generated by Django 5.2.1 on 2025-05-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_bag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingbag',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
