# Generated by Django 5.2.1 on 2025-06-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredential',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with this username already exists.'}, max_length=150, unique=True),
        ),
    ]
