# Generated by Django 5.2.1 on 2025-06-26 17:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphoto',
            name='photo',
            field=cloudinary.models.CloudinaryField(default='image/upload/v1750959197/user-1699635_1280_z3dgxn.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
