# Generated by Django 5.2.1 on 2025-07-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userphoto_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredential',
            name='agreed_to_emails',
            field=models.BooleanField(default=False),
        ),
    ]
