# Generated by Django 5.2.1 on 2025-06-27 13:01

import src.accounts.validators.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usercredential_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredential',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with this username already exists.'}, max_length=150, unique=True, validators=[src.accounts.validators.models.UsernameValidator()]),
        ),
    ]
